// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_SDM

Testing SubscriptionModificationAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Nudm_SDM

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_Nudm_SDM_SubscriptionModificationAPIService(t *testing.T) {

	configuration := NewConfiguration()
	apiClient := NewAPIClient(configuration)

	t.Run("Test SubscriptionModificationAPIService Modify", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var ueId string
		var subscriptionId string

		resp, httpRes, err := apiClient.SubscriptionModificationAPI.Modify(context.Background(), ueId, subscriptionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test SubscriptionModificationAPIService ModifySharedDataSubs", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var subscriptionId string

		resp, httpRes, err := apiClient.SubscriptionModificationAPI.ModifySharedDataSubs(context.Background(), subscriptionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

}
