// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_SDM

Testing SubscriptionDeletionAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Nudm_SDM

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_Nudm_SDM_SubscriptionDeletionAPIService(t *testing.T) {

	configuration := NewConfiguration()
	apiClient := NewAPIClient(configuration)

	t.Run("Test SubscriptionDeletionAPIService Unsubscribe", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var ueId string
		var subscriptionId string

		httpRes, err := apiClient.SubscriptionDeletionAPI.Unsubscribe(context.Background(), ueId, subscriptionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

}
