// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_SDM

Nudm Subscriber Data Management Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nudm_SDM

import (
	"encoding/json"
)

// checks if the Ssm type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Ssm{}

// Ssm Source specific IP multicast address
type Ssm struct {
	SourceIpAddr         NullableIpAddr `json:"sourceIpAddr"`
	DestIpAddr           NullableIpAddr `json:"destIpAddr"`
	AdditionalProperties map[string]interface{}
}

type _Ssm Ssm

// NewSsm instantiates a new Ssm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSsm(sourceIpAddr NullableIpAddr, destIpAddr NullableIpAddr) *Ssm {
	this := Ssm{}
	this.SourceIpAddr = sourceIpAddr
	this.DestIpAddr = destIpAddr
	return &this
}

// NewSsmWithDefaults instantiates a new Ssm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSsmWithDefaults() *Ssm {
	this := Ssm{}
	return &this
}

// GetSourceIpAddr returns the SourceIpAddr field value
// If the value is explicit nil, the zero value for IpAddr will be returned
func (o *Ssm) GetSourceIpAddr() IpAddr {
	if o == nil || o.SourceIpAddr.Get() == nil {
		var ret IpAddr
		return ret
	}

	return *o.SourceIpAddr.Get()
}

// GetSourceIpAddrOk returns a tuple with the SourceIpAddr field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Ssm) GetSourceIpAddrOk() (*IpAddr, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceIpAddr.Get(), o.SourceIpAddr.IsSet()
}

// SetSourceIpAddr sets field value
func (o *Ssm) SetSourceIpAddr(v IpAddr) {
	o.SourceIpAddr.Set(&v)
}

// GetDestIpAddr returns the DestIpAddr field value
// If the value is explicit nil, the zero value for IpAddr will be returned
func (o *Ssm) GetDestIpAddr() IpAddr {
	if o == nil || o.DestIpAddr.Get() == nil {
		var ret IpAddr
		return ret
	}

	return *o.DestIpAddr.Get()
}

// GetDestIpAddrOk returns a tuple with the DestIpAddr field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Ssm) GetDestIpAddrOk() (*IpAddr, bool) {
	if o == nil {
		return nil, false
	}
	return o.DestIpAddr.Get(), o.DestIpAddr.IsSet()
}

// SetDestIpAddr sets field value
func (o *Ssm) SetDestIpAddr(v IpAddr) {
	o.DestIpAddr.Set(&v)
}

func (o Ssm) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sourceIpAddr"] = o.SourceIpAddr.Get()
	toSerialize["destIpAddr"] = o.DestIpAddr.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableSsm struct {
	value *Ssm
	isSet bool
}

func (v NullableSsm) Get() *Ssm {
	return v.value
}

func (v *NullableSsm) Set(val *Ssm) {
	v.value = val
	v.isSet = true
}

func (v NullableSsm) IsSet() bool {
	return v.isSet
}

func (v *NullableSsm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSsm(val *Ssm) *NullableSsm {
	return &NullableSsm{value: val, isSet: true}
}

func (v NullableSsm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSsm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
