// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_SDM

Nudm Subscriber Data Management Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nudm_SDM

import (
	"encoding/json"
)

// checks if the SupiInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SupiInfo{}

// SupiInfo List of Supis.
type SupiInfo struct {
	SupiList             []string `json:"supiList"`
	AdditionalProperties map[string]interface{}
}

type _SupiInfo SupiInfo

// NewSupiInfo instantiates a new SupiInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSupiInfo(supiList []string) *SupiInfo {
	this := SupiInfo{}
	this.SupiList = supiList
	return &this
}

// NewSupiInfoWithDefaults instantiates a new SupiInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSupiInfoWithDefaults() *SupiInfo {
	this := SupiInfo{}
	return &this
}

// GetSupiList returns the SupiList field value
func (o *SupiInfo) GetSupiList() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SupiList
}

// GetSupiListOk returns a tuple with the SupiList field value
// and a boolean to check if the value has been set.
func (o *SupiInfo) GetSupiListOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SupiList, true
}

// SetSupiList sets field value
func (o *SupiInfo) SetSupiList(v []string) {
	o.SupiList = v
}

func (o SupiInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["supiList"] = o.SupiList

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableSupiInfo struct {
	value *SupiInfo
	isSet bool
}

func (v NullableSupiInfo) Get() *SupiInfo {
	return v.value
}

func (v *NullableSupiInfo) Set(val *SupiInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableSupiInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableSupiInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupiInfo(val *SupiInfo) *NullableSupiInfo {
	return &NullableSupiInfo{value: val, isSet: true}
}

func (v NullableSupiInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupiInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
