// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_SDM

Nudm Subscriber Data Management Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nudm_SDM

import (
	"encoding/json"
)

// checks if the PointUncertaintyEllipse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PointUncertaintyEllipse{}

// PointUncertaintyEllipse Ellipsoid point with uncertainty ellipse.
type PointUncertaintyEllipse struct {
	GADShape
	Point              *GeographicalCoordinates `json:"point,omitempty"`
	UncertaintyEllipse *UncertaintyEllipse      `json:"uncertaintyEllipse,omitempty"`
	// Indicates value of confidence.
	Confidence           *int32 `json:"confidence,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PointUncertaintyEllipse PointUncertaintyEllipse

// NewPointUncertaintyEllipse instantiates a new PointUncertaintyEllipse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPointUncertaintyEllipse(shape SupportedGADShapes) *PointUncertaintyEllipse {
	this := PointUncertaintyEllipse{}
	this.Shape = shape
	return &this
}

// NewPointUncertaintyEllipseWithDefaults instantiates a new PointUncertaintyEllipse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPointUncertaintyEllipseWithDefaults() *PointUncertaintyEllipse {
	this := PointUncertaintyEllipse{}
	return &this
}

// GetPoint returns the Point field value if set, zero value otherwise.
func (o *PointUncertaintyEllipse) GetPoint() GeographicalCoordinates {
	if o == nil || IsNil(o.Point) {
		var ret GeographicalCoordinates
		return ret
	}
	return *o.Point
}

// GetPointOk returns a tuple with the Point field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointUncertaintyEllipse) GetPointOk() (*GeographicalCoordinates, bool) {
	if o == nil || IsNil(o.Point) {
		return nil, false
	}
	return o.Point, true
}

// HasPoint returns a boolean if a field has been set.
func (o *PointUncertaintyEllipse) HasPoint() bool {
	if o != nil && !IsNil(o.Point) {
		return true
	}

	return false
}

// SetPoint gets a reference to the given GeographicalCoordinates and assigns it to the Point field.
func (o *PointUncertaintyEllipse) SetPoint(v GeographicalCoordinates) {
	o.Point = &v
}

// GetUncertaintyEllipse returns the UncertaintyEllipse field value if set, zero value otherwise.
func (o *PointUncertaintyEllipse) GetUncertaintyEllipse() UncertaintyEllipse {
	if o == nil || IsNil(o.UncertaintyEllipse) {
		var ret UncertaintyEllipse
		return ret
	}
	return *o.UncertaintyEllipse
}

// GetUncertaintyEllipseOk returns a tuple with the UncertaintyEllipse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointUncertaintyEllipse) GetUncertaintyEllipseOk() (*UncertaintyEllipse, bool) {
	if o == nil || IsNil(o.UncertaintyEllipse) {
		return nil, false
	}
	return o.UncertaintyEllipse, true
}

// HasUncertaintyEllipse returns a boolean if a field has been set.
func (o *PointUncertaintyEllipse) HasUncertaintyEllipse() bool {
	if o != nil && !IsNil(o.UncertaintyEllipse) {
		return true
	}

	return false
}

// SetUncertaintyEllipse gets a reference to the given UncertaintyEllipse and assigns it to the UncertaintyEllipse field.
func (o *PointUncertaintyEllipse) SetUncertaintyEllipse(v UncertaintyEllipse) {
	o.UncertaintyEllipse = &v
}

// GetConfidence returns the Confidence field value if set, zero value otherwise.
func (o *PointUncertaintyEllipse) GetConfidence() int32 {
	if o == nil || IsNil(o.Confidence) {
		var ret int32
		return ret
	}
	return *o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointUncertaintyEllipse) GetConfidenceOk() (*int32, bool) {
	if o == nil || IsNil(o.Confidence) {
		return nil, false
	}
	return o.Confidence, true
}

// HasConfidence returns a boolean if a field has been set.
func (o *PointUncertaintyEllipse) HasConfidence() bool {
	if o != nil && !IsNil(o.Confidence) {
		return true
	}

	return false
}

// SetConfidence gets a reference to the given int32 and assigns it to the Confidence field.
func (o *PointUncertaintyEllipse) SetConfidence(v int32) {
	o.Confidence = &v
}

func (o PointUncertaintyEllipse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedGADShape, errGADShape := json.Marshal(o.GADShape)
	if errGADShape != nil {
		return map[string]interface{}{}, errGADShape
	}
	errGADShape = json.Unmarshal([]byte(serializedGADShape), &toSerialize)
	if errGADShape != nil {
		return map[string]interface{}{}, errGADShape
	}
	if !IsNil(o.Point) {
		toSerialize["point"] = o.Point
	}
	if !IsNil(o.UncertaintyEllipse) {
		toSerialize["uncertaintyEllipse"] = o.UncertaintyEllipse
	}
	if !IsNil(o.Confidence) {
		toSerialize["confidence"] = o.Confidence
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullablePointUncertaintyEllipse struct {
	value *PointUncertaintyEllipse
	isSet bool
}

func (v NullablePointUncertaintyEllipse) Get() *PointUncertaintyEllipse {
	return v.value
}

func (v *NullablePointUncertaintyEllipse) Set(val *PointUncertaintyEllipse) {
	v.value = val
	v.isSet = true
}

func (v NullablePointUncertaintyEllipse) IsSet() bool {
	return v.isSet
}

func (v *NullablePointUncertaintyEllipse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePointUncertaintyEllipse(val *PointUncertaintyEllipse) *NullablePointUncertaintyEllipse {
	return &NullablePointUncertaintyEllipse{value: val, isSet: true}
}

func (v NullablePointUncertaintyEllipse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePointUncertaintyEllipse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
