// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_SDM

Nudm Subscriber Data Management Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nudm_SDM

import (
	"encoding/json"
)

// checks if the UcSubscriptionData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UcSubscriptionData{}

// UcSubscriptionData Contains the User Consent Subscription Data.
type UcSubscriptionData struct {
	// A map(list of key-value pairs) where user consent purpose serves as key of user consent
	UserConsentPerPurposeList map[string]UserConsent `json:"userConsentPerPurposeList,omitempty"`
	AdditionalProperties      map[string]interface{}
}

type _UcSubscriptionData UcSubscriptionData

// NewUcSubscriptionData instantiates a new UcSubscriptionData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUcSubscriptionData() *UcSubscriptionData {
	this := UcSubscriptionData{}
	return &this
}

// NewUcSubscriptionDataWithDefaults instantiates a new UcSubscriptionData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUcSubscriptionDataWithDefaults() *UcSubscriptionData {
	this := UcSubscriptionData{}
	return &this
}

// GetUserConsentPerPurposeList returns the UserConsentPerPurposeList field value if set, zero value otherwise.
func (o *UcSubscriptionData) GetUserConsentPerPurposeList() map[string]UserConsent {
	if o == nil || IsNil(o.UserConsentPerPurposeList) {
		var ret map[string]UserConsent
		return ret
	}
	return o.UserConsentPerPurposeList
}

// GetUserConsentPerPurposeListOk returns a tuple with the UserConsentPerPurposeList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UcSubscriptionData) GetUserConsentPerPurposeListOk() (map[string]UserConsent, bool) {
	if o == nil || IsNil(o.UserConsentPerPurposeList) {
		return map[string]UserConsent{}, false
	}
	return o.UserConsentPerPurposeList, true
}

// HasUserConsentPerPurposeList returns a boolean if a field has been set.
func (o *UcSubscriptionData) HasUserConsentPerPurposeList() bool {
	if o != nil && !IsNil(o.UserConsentPerPurposeList) {
		return true
	}

	return false
}

// SetUserConsentPerPurposeList gets a reference to the given map[string]UserConsent and assigns it to the UserConsentPerPurposeList field.
func (o *UcSubscriptionData) SetUserConsentPerPurposeList(v map[string]UserConsent) {
	o.UserConsentPerPurposeList = v
}

func (o UcSubscriptionData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserConsentPerPurposeList) {
		toSerialize["userConsentPerPurposeList"] = o.UserConsentPerPurposeList
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableUcSubscriptionData struct {
	value *UcSubscriptionData
	isSet bool
}

func (v NullableUcSubscriptionData) Get() *UcSubscriptionData {
	return v.value
}

func (v *NullableUcSubscriptionData) Set(val *UcSubscriptionData) {
	v.value = val
	v.isSet = true
}

func (v NullableUcSubscriptionData) IsSet() bool {
	return v.isSet
}

func (v *NullableUcSubscriptionData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUcSubscriptionData(val *UcSubscriptionData) *NullableUcSubscriptionData {
	return &NullableUcSubscriptionData{value: val, isSet: true}
}

func (v NullableUcSubscriptionData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUcSubscriptionData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
