// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_SDM

Nudm Subscriber Data Management Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nudm_SDM

import (
	"encoding/json"
	"fmt"
)

// UserConsent Indicates user’s consent.
type UserConsent string

// List of UserConsent
const (
	USERCONSENT_NOT_GIVEN UserConsent = "CONSENT_NOT_GIVEN"
	USERCONSENT_GIVEN     UserConsent = "CONSENT_GIVEN"
)

// All allowed values of UserConsent enum
var AllowedUserConsentEnumValues = []UserConsent{
	"CONSENT_NOT_GIVEN",
	"CONSENT_GIVEN",
}

func (v *UserConsent) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := UserConsent(value)
	for _, existing := range AllowedUserConsentEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid UserConsent", value)
}

// NewUserConsentFromValue returns a pointer to a valid UserConsent
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewUserConsentFromValue(v string) (*UserConsent, error) {
	ev := UserConsent(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for UserConsent: valid values are %v", v, AllowedUserConsentEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v UserConsent) IsValid() bool {
	for _, existing := range AllowedUserConsentEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to UserConsent value
func (v UserConsent) Ptr() *UserConsent {
	return &v
}

type NullableUserConsent struct {
	value *UserConsent
	isSet bool
}

func (v NullableUserConsent) Get() *UserConsent {
	return v.value
}

func (v *NullableUserConsent) Set(val *UserConsent) {
	v.value = val
	v.isSet = true
}

func (v NullableUserConsent) IsSet() bool {
	return v.isSet
}

func (v *NullableUserConsent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserConsent(val *UserConsent) *NullableUserConsent {
	return &NullableUserConsent{value: val, isSet: true}
}

func (v NullableUserConsent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserConsent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
