// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_SDM

Nudm Subscriber Data Management Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nudm_SDM

import (
	"encoding/json"
)

// checks if the DnnLadnServiceAreas type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DnnLadnServiceAreas{}

// DnnLadnServiceAreas struct for DnnLadnServiceAreas
type DnnLadnServiceAreas struct {
	DnnLadnServiceAreas  []DnnLadnServiceArea `json:"dnnLadnServiceAreas"`
	AdditionalProperties map[string]interface{}
}

type _DnnLadnServiceAreas DnnLadnServiceAreas

// NewDnnLadnServiceAreas instantiates a new DnnLadnServiceAreas object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDnnLadnServiceAreas(dnnLadnServiceAreas []DnnLadnServiceArea) *DnnLadnServiceAreas {
	this := DnnLadnServiceAreas{}
	this.DnnLadnServiceAreas = dnnLadnServiceAreas
	return &this
}

// NewDnnLadnServiceAreasWithDefaults instantiates a new DnnLadnServiceAreas object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDnnLadnServiceAreasWithDefaults() *DnnLadnServiceAreas {
	this := DnnLadnServiceAreas{}
	return &this
}

// GetDnnLadnServiceAreas returns the DnnLadnServiceAreas field value
func (o *DnnLadnServiceAreas) GetDnnLadnServiceAreas() []DnnLadnServiceArea {
	if o == nil {
		var ret []DnnLadnServiceArea
		return ret
	}

	return o.DnnLadnServiceAreas
}

// GetDnnLadnServiceAreasOk returns a tuple with the DnnLadnServiceAreas field value
// and a boolean to check if the value has been set.
func (o *DnnLadnServiceAreas) GetDnnLadnServiceAreasOk() ([]DnnLadnServiceArea, bool) {
	if o == nil {
		return nil, false
	}
	return o.DnnLadnServiceAreas, true
}

// SetDnnLadnServiceAreas sets field value
func (o *DnnLadnServiceAreas) SetDnnLadnServiceAreas(v []DnnLadnServiceArea) {
	o.DnnLadnServiceAreas = v
}

func (o DnnLadnServiceAreas) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dnnLadnServiceAreas"] = o.DnnLadnServiceAreas

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableDnnLadnServiceAreas struct {
	value *DnnLadnServiceAreas
	isSet bool
}

func (v NullableDnnLadnServiceAreas) Get() *DnnLadnServiceAreas {
	return v.value
}

func (v *NullableDnnLadnServiceAreas) Set(val *DnnLadnServiceAreas) {
	v.value = val
	v.isSet = true
}

func (v NullableDnnLadnServiceAreas) IsSet() bool {
	return v.isSet
}

func (v *NullableDnnLadnServiceAreas) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDnnLadnServiceAreas(val *DnnLadnServiceAreas) *NullableDnnLadnServiceAreas {
	return &NullableDnnLadnServiceAreas{value: val, isSet: true}
}

func (v NullableDnnLadnServiceAreas) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDnnLadnServiceAreas) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
