// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
NRF NFManagement Service

Testing SubscriptionIDDocumentAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Nnrf_NFManagement

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_Nnrf_NFManagement_SubscriptionIDDocumentAPIService(t *testing.T) {

	configuration := NewConfiguration()
	apiClient := NewAPIClient(configuration)

	t.Run("Test SubscriptionIDDocumentAPIService RemoveSubscription", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var subscriptionID string

		httpRes, err := apiClient.SubscriptionIDDocumentAPI.RemoveSubscription(context.Background(), subscriptionID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test SubscriptionIDDocumentAPIService UpdateSubscription", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var subscriptionID string

		resp, httpRes, err := apiClient.SubscriptionIDDocumentAPI.UpdateSubscription(context.Background(), subscriptionID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

}
