// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
NRF NFManagement Service

NRF NFManagement Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nnrf_NFManagement

import (
	"encoding/json"
	"fmt"
)

// RuleSetAction the model 'RuleSetAction'
type RuleSetAction string

// List of RuleSetAction
const (
	RULESETACTION_ALLOW RuleSetAction = "ALLOW"
	RULESETACTION_DENY  RuleSetAction = "DENY"
)

// All allowed values of RuleSetAction enum
var AllowedRuleSetActionEnumValues = []RuleSetAction{
	"ALLOW",
	"DENY",
}

func (v *RuleSetAction) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RuleSetAction(value)
	for _, existing := range AllowedRuleSetActionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RuleSetAction", value)
}

// NewRuleSetActionFromValue returns a pointer to a valid RuleSetAction
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRuleSetActionFromValue(v string) (*RuleSetAction, error) {
	ev := RuleSetAction(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RuleSetAction: valid values are %v", v, AllowedRuleSetActionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RuleSetAction) IsValid() bool {
	for _, existing := range AllowedRuleSetActionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RuleSetAction value
func (v RuleSetAction) Ptr() *RuleSetAction {
	return &v
}

type NullableRuleSetAction struct {
	value *RuleSetAction
	isSet bool
}

func (v NullableRuleSetAction) Get() *RuleSetAction {
	return v.value
}

func (v *NullableRuleSetAction) Set(val *RuleSetAction) {
	v.value = val
	v.isSet = true
}

func (v NullableRuleSetAction) IsSet() bool {
	return v.isSet
}

func (v *NullableRuleSetAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRuleSetAction(val *RuleSetAction) *NullableRuleSetAction {
	return &NullableRuleSetAction{value: val, isSet: true}
}

func (v NullableRuleSetAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRuleSetAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
