// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
NRF NFManagement Service

NRF NFManagement Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nnrf_NFManagement

import (
	"encoding/json"
	"fmt"
)

// AfEvent Represents an application's event.   Possible values are: - SVC_EXPERIENCE: Indicates that the subscribed/notified event is service experience   information for an application. - UE_MOBILITY: Indicates that the subscribed/notified event is UE mobility information. - UE_COMM: Indicates that the subscribed/notified event is UE communication information. - EXCEPTIONS: Indicates that the subscribed/notified event is exceptions information. - USER_DATA_CONGESTION: Indicates that the subscribed/notified event is user data congestion   analytics related information. - PERF_DATA: Indicates that the subscribed/notified event is performance data information. - DISPERSION: Indicates that the subscribed/notified event is dispersion information. - COLLECTIVE_BEHAVIOUR: Indicates that the subscribed/notified event is collective behaviour   information. - MS_QOE_METRICS: Indicates that the subscribed/notified event is Media Streaming QoE   metrics. - MS_CONSUMPTION: Indicates that the subscribed/notified event is Media Streaming   consumption reports. - MS_NET_ASSIST_INVOCATION: Indicates that the subscribed/notified event is Media Streaming   network assistance invocation. - MS_DYN_POLICY_INVOCATION: Indicates that the subscribed/notified event is Media Streaming   dynamic policy invocation. - MS_ACCESS_ACTIVITY: Indicates that the subscribed/notified event is Media Streaming access   activity. - GNSS_ASSISTANCE_DATA: Indicates that the subscribed/notified event is GNSS Assistance Data   Collection.
type AfEvent struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *AfEvent) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(AfEvent)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *AfEvent) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableAfEvent struct {
	value *AfEvent
	isSet bool
}

func (v NullableAfEvent) Get() *AfEvent {
	return v.value
}

func (v *NullableAfEvent) Set(val *AfEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableAfEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableAfEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAfEvent(val *AfEvent) *NullableAfEvent {
	return &NullableAfEvent{value: val, isSet: true}
}

func (v NullableAfEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAfEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
