// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
NRF NFManagement Service

NRF NFManagement Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nnrf_NFManagement

import (
	"encoding/json"
)

// checks if the SharedDataIdList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SharedDataIdList{}

// SharedDataIdList Shared Data IDs
type SharedDataIdList struct {
	SharedDataIds        []string `json:"sharedDataIds"`
	AdditionalProperties map[string]interface{}
}

type _SharedDataIdList SharedDataIdList

// NewSharedDataIdList instantiates a new SharedDataIdList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSharedDataIdList(sharedDataIds []string) *SharedDataIdList {
	this := SharedDataIdList{}
	this.SharedDataIds = sharedDataIds
	return &this
}

// NewSharedDataIdListWithDefaults instantiates a new SharedDataIdList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSharedDataIdListWithDefaults() *SharedDataIdList {
	this := SharedDataIdList{}
	return &this
}

// GetSharedDataIds returns the SharedDataIds field value
func (o *SharedDataIdList) GetSharedDataIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SharedDataIds
}

// GetSharedDataIdsOk returns a tuple with the SharedDataIds field value
// and a boolean to check if the value has been set.
func (o *SharedDataIdList) GetSharedDataIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SharedDataIds, true
}

// SetSharedDataIds sets field value
func (o *SharedDataIdList) SetSharedDataIds(v []string) {
	o.SharedDataIds = v
}

func (o SharedDataIdList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sharedDataIds"] = o.SharedDataIds

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableSharedDataIdList struct {
	value *SharedDataIdList
	isSet bool
}

func (v NullableSharedDataIdList) Get() *SharedDataIdList {
	return v.value
}

func (v *NullableSharedDataIdList) Set(val *SharedDataIdList) {
	v.value = val
	v.isSet = true
}

func (v NullableSharedDataIdList) IsSet() bool {
	return v.isSet
}

func (v *NullableSharedDataIdList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSharedDataIdList(val *SharedDataIdList) *NullableSharedDataIdList {
	return &NullableSharedDataIdList{value: val, isSet: true}
}

func (v NullableSharedDataIdList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSharedDataIdList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
