// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

Testing IndividualSMContextAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Nsmf_PDUSession

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_Nsmf_PDUSession_IndividualSMContextAPIService(t *testing.T) {

	configuration := NewConfiguration()
	apiClient := NewAPIClient(configuration)

	t.Run("Test IndividualSMContextAPIService ReleaseSmContext", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var smContextRef string

		resp, httpRes, err := apiClient.IndividualSMContextAPI.ReleaseSmContext(context.Background(), smContextRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test IndividualSMContextAPIService RetrieveSmContext", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var smContextRef string

		resp, httpRes, err := apiClient.IndividualSMContextAPI.RetrieveSmContext(context.Background(), smContextRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test IndividualSMContextAPIService SendMoData", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var smContextRef string

		httpRes, err := apiClient.IndividualSMContextAPI.SendMoData(context.Background(), smContextRef).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test IndividualSMContextAPIService UpdateSmContext", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var smContextRef string

		resp, httpRes, err := apiClient.IndividualSMContextAPI.UpdateSmContext(context.Background(), smContextRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

}
