// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

Testing IndividualPDUSessionHSMFOrSMFAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Nsmf_PDUSession

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_Nsmf_PDUSession_IndividualPDUSessionHSMFOrSMFAPIService(t *testing.T) {

	configuration := NewConfiguration()
	apiClient := NewAPIClient(configuration)

	t.Run("Test IndividualPDUSessionHSMFOrSMFAPIService ReleasePduSession", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var pduSessionRef string

		resp, httpRes, err := apiClient.IndividualPDUSessionHSMFOrSMFAPI.ReleasePduSession(context.Background(), pduSessionRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test IndividualPDUSessionHSMFOrSMFAPIService RetrievePduSession", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var pduSessionRef string

		resp, httpRes, err := apiClient.IndividualPDUSessionHSMFOrSMFAPI.RetrievePduSession(context.Background(), pduSessionRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test IndividualPDUSessionHSMFOrSMFAPIService TransferMoData", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var pduSessionRef string

		httpRes, err := apiClient.IndividualPDUSessionHSMFOrSMFAPI.TransferMoData(context.Background(), pduSessionRef).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test IndividualPDUSessionHSMFOrSMFAPIService UpdatePduSession", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var pduSessionRef string

		resp, httpRes, err := apiClient.IndividualPDUSessionHSMFOrSMFAPI.UpdatePduSession(context.Background(), pduSessionRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

}
