// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

SMF PDU Session Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nsmf_PDUSession

import (
	"encoding/json"
	"fmt"
)

// UpCnxState User Plane Connection State. Possible values are - ACTIVATED - DEACTIVATED - ACTIVATING - SUSPENDED
type UpCnxState string

// List of UpCnxState
const (
	UPCNXSTATE_ACTIVATED   UpCnxState = "ACTIVATED"
	UPCNXSTATE_DEACTIVATED UpCnxState = "DEACTIVATED"
	UPCNXSTATE_ACTIVATING  UpCnxState = "ACTIVATING"
	UPCNXSTATE_SUSPENDED   UpCnxState = "SUSPENDED"
)

// All allowed values of UpCnxState enum
var AllowedUpCnxStateEnumValues = []UpCnxState{
	"ACTIVATED",
	"DEACTIVATED",
	"ACTIVATING",
	"SUSPENDED",
}

func (v *UpCnxState) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := UpCnxState(value)
	for _, existing := range AllowedUpCnxStateEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid UpCnxState", value)
}

// NewUpCnxStateFromValue returns a pointer to a valid UpCnxState
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewUpCnxStateFromValue(v string) (*UpCnxState, error) {
	ev := UpCnxState(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for UpCnxState: valid values are %v", v, AllowedUpCnxStateEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v UpCnxState) IsValid() bool {
	for _, existing := range AllowedUpCnxStateEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to UpCnxState value
func (v UpCnxState) Ptr() *UpCnxState {
	return &v
}

type NullableUpCnxState struct {
	value *UpCnxState
	isSet bool
}

func (v NullableUpCnxState) Get() *UpCnxState {
	return v.value
}

func (v *NullableUpCnxState) Set(val *UpCnxState) {
	v.value = val
	v.isSet = true
}

func (v NullableUpCnxState) IsSet() bool {
	return v.isSet
}

func (v *NullableUpCnxState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpCnxState(val *UpCnxState) *NullableUpCnxState {
	return &NullableUpCnxState{value: val, isSet: true}
}

func (v NullableUpCnxState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpCnxState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
