// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

SMF PDU Session Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nsmf_PDUSession

import (
	"encoding/json"
)

// checks if the Ipv6AddressRange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Ipv6AddressRange{}

// Ipv6AddressRange Range of IPv6 addresses
type Ipv6AddressRange struct {
	Start                Ipv6Addr `json:"start"`
	End                  Ipv6Addr `json:"end"`
	AdditionalProperties map[string]interface{}
}

type _Ipv6AddressRange Ipv6AddressRange

// NewIpv6AddressRange instantiates a new Ipv6AddressRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIpv6AddressRange(start Ipv6Addr, end Ipv6Addr) *Ipv6AddressRange {
	this := Ipv6AddressRange{}
	this.Start = start
	this.End = end
	return &this
}

// NewIpv6AddressRangeWithDefaults instantiates a new Ipv6AddressRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIpv6AddressRangeWithDefaults() *Ipv6AddressRange {
	this := Ipv6AddressRange{}
	return &this
}

// GetStart returns the Start field value
func (o *Ipv6AddressRange) GetStart() Ipv6Addr {
	if o == nil {
		var ret Ipv6Addr
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *Ipv6AddressRange) GetStartOk() (*Ipv6Addr, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *Ipv6AddressRange) SetStart(v Ipv6Addr) {
	o.Start = v
}

// GetEnd returns the End field value
func (o *Ipv6AddressRange) GetEnd() Ipv6Addr {
	if o == nil {
		var ret Ipv6Addr
		return ret
	}

	return o.End
}

// GetEndOk returns a tuple with the End field value
// and a boolean to check if the value has been set.
func (o *Ipv6AddressRange) GetEndOk() (*Ipv6Addr, bool) {
	if o == nil {
		return nil, false
	}
	return &o.End, true
}

// SetEnd sets field value
func (o *Ipv6AddressRange) SetEnd(v Ipv6Addr) {
	o.End = v
}

func (o Ipv6AddressRange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["start"] = o.Start
	toSerialize["end"] = o.End

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableIpv6AddressRange struct {
	value *Ipv6AddressRange
	isSet bool
}

func (v NullableIpv6AddressRange) Get() *Ipv6AddressRange {
	return v.value
}

func (v *NullableIpv6AddressRange) Set(val *Ipv6AddressRange) {
	v.value = val
	v.isSet = true
}

func (v NullableIpv6AddressRange) IsSet() bool {
	return v.isSet
}

func (v *NullableIpv6AddressRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpv6AddressRange(val *Ipv6AddressRange) *NullableIpv6AddressRange {
	return &NullableIpv6AddressRange{value: val, isSet: true}
}

func (v NullableIpv6AddressRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpv6AddressRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
