// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

SMF PDU Session Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nsmf_PDUSession

import (
	"encoding/json"
	"fmt"
)

// Cause Cause information. Possible values are - REL_DUE_TO_HO - EPS_FALLBACK - REL_DUE_TO_UP_SEC - DNN_CONGESTION - S_NSSAI_CONGESTION - REL_DUE_TO_REACTIVATION - 5G_AN_NOT_RESPONDING - REL_DUE_TO_SLICE_NOT_AVAILABLE - REL_DUE_TO_DUPLICATE_SESSION_ID - PDU_SESSION_STATUS_MISMATCH - HO_FAILURE - INSUFFICIENT_UP_RESOURCES - PDU_SESSION_HANDED_OVER - PDU_SESSION_RESUMED - CN_ASSISTED_RAN_PARAMETER_TUNING - ISMF_CONTEXT_TRANSFER - SMF_CONTEXT_TRANSFER - REL_DUE_TO_PS_TO_CS_HO - REL_DUE_TO_SUBSCRIPTION_CHANGE - HO_CANCEL - REL_DUE_TO_SLICE_NOT_AUTHORIZED - PDU_SESSION_HAND_OVER_FAILURE - DDN_FAILURE_STATUS - REL_DUE_TO_CP_ONLY_NOT_APPLICABLE - NOT_SUPPORTED_WITH_ISMF - CHANGED_ANCHOR_SMF - CHANGED_INTERMEDIATE_SMF - TARGET_DNAI_NOTIFICATION - REL_DUE_TO_VPLMN_QOS_FAILURE - REL_DUE_TO_SMF_NOT_SUPPORT_PSETR - REL_DUE_TO_SNPN_SNPN_MOBILITY - REL_DUE_TO_NO_HR_AGREEMENT - REL_DUE_TO_UNSPECIFIED_REASON - REL_DUE_TO_MOB_ACCESS_RESTRICTIONS - REL_DUE_TO_SLICE_INACTIVITY - REL_DUE_TO_NSI_NOT_AVAILABLE - REL_DUE_TO_DNN_DENIED - REL_DUE_TO_PDUTYPE_DENIED - REL_DUE_TO_SSC_DENIED - REL_DUE_TO_SUBSCRIPTION_DENIED - REL_DUE_TO_DNN_NOT_SUPPORTED - REL_DUE_TO_PDUTYPE_NOT_SUPPORTED - REL_DUE_TO_SSC_NOT_SUPPORTED - REL_DUE_TO_INSUFFICIENT_RESOURCES_SLICE - REL_DUE_TO_INSUFFICIENT_RESOURCES_SLICE_DNN - REL_DUE_TO_DNN_CONGESTION - REL_DUE_TO_S_NSSAI_CONGESTION - REL_DUE_TO_PEER_NOT_RESPONDING - REL_DUE_TO_NETWORK_FAILURE - REL_DUE_TO_UPF_NOT_RESPONDING - REL_DUE_TO_NO_EPS_5GS_CONTINUITY - REL_DUE_TO_NOT_SUPPORTED_WITH_ISMF - REL_DUE_TO_EXCEEDED_UE_SLICE_DATA_RATE - REL_DUE_TO_EXCEEDED_SLICE_DATA_RATE - REL_DUE_TO_CONTEXT_NOT_FOUND - REL_DUE_TO_MBSR_NOT_AUTHORIZED - DEACT_DUE_TO_UE_OUT_OF_SLICE_SUPPORT_AREA - REJECT_DUE_TO_N1_SM_ERROR
type Cause struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Cause) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(Cause)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *Cause) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableCause struct {
	value *Cause
	isSet bool
}

func (v NullableCause) Get() *Cause {
	return v.value
}

func (v *NullableCause) Set(val *Cause) {
	v.value = val
	v.isSet = true
}

func (v NullableCause) IsSet() bool {
	return v.isSet
}

func (v *NullableCause) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCause(val *Cause) *NullableCause {
	return &NullableCause{value: val, isSet: true}
}

func (v NullableCause) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCause) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
