// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

SMF PDU Session Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nsmf_PDUSession

import (
	"encoding/json"
	"fmt"
)

// EcnMarkingReq ECN Marking Request Type. Possible values are - UL - DL - BOTH - STOP
type EcnMarkingReq string

// List of EcnMarkingReq
const (
	ECNMARKINGREQ_UL   EcnMarkingReq = "UL"
	ECNMARKINGREQ_DL   EcnMarkingReq = "DL"
	ECNMARKINGREQ_BOTH EcnMarkingReq = "BOTH"
	ECNMARKINGREQ_STOP EcnMarkingReq = "STOP"
)

// All allowed values of EcnMarkingReq enum
var AllowedEcnMarkingReqEnumValues = []EcnMarkingReq{
	"UL",
	"DL",
	"BOTH",
	"STOP",
}

func (v *EcnMarkingReq) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EcnMarkingReq(value)
	for _, existing := range AllowedEcnMarkingReqEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EcnMarkingReq", value)
}

// NewEcnMarkingReqFromValue returns a pointer to a valid EcnMarkingReq
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEcnMarkingReqFromValue(v string) (*EcnMarkingReq, error) {
	ev := EcnMarkingReq(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EcnMarkingReq: valid values are %v", v, AllowedEcnMarkingReqEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EcnMarkingReq) IsValid() bool {
	for _, existing := range AllowedEcnMarkingReqEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EcnMarkingReq value
func (v EcnMarkingReq) Ptr() *EcnMarkingReq {
	return &v
}

type NullableEcnMarkingReq struct {
	value *EcnMarkingReq
	isSet bool
}

func (v NullableEcnMarkingReq) Get() *EcnMarkingReq {
	return v.value
}

func (v *NullableEcnMarkingReq) Set(val *EcnMarkingReq) {
	v.value = val
	v.isSet = true
}

func (v NullableEcnMarkingReq) IsSet() bool {
	return v.isSet
}

func (v *NullableEcnMarkingReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEcnMarkingReq(val *EcnMarkingReq) *NullableEcnMarkingReq {
	return &NullableEcnMarkingReq{value: val, isSet: true}
}

func (v NullableEcnMarkingReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEcnMarkingReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
