// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

SMF PDU Session Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nsmf_PDUSession

import (
	"encoding/json"
	"fmt"
)

// UpIntegrity indicates whether UP integrity protection is required, preferred or not needed for all the traffic on the PDU Session. It shall comply with the provisions defined in  table 5.4.3.4-1.
type UpIntegrity string

// List of UpIntegrity
const (
	UPINTEGRITY_REQUIRED   UpIntegrity = "REQUIRED"
	UPINTEGRITY_PREFERRED  UpIntegrity = "PREFERRED"
	UPINTEGRITY_NOT_NEEDED UpIntegrity = "NOT_NEEDED"
)

// All allowed values of UpIntegrity enum
var AllowedUpIntegrityEnumValues = []UpIntegrity{
	"REQUIRED",
	"PREFERRED",
	"NOT_NEEDED",
}

func (v *UpIntegrity) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := UpIntegrity(value)
	for _, existing := range AllowedUpIntegrityEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid UpIntegrity", value)
}

// NewUpIntegrityFromValue returns a pointer to a valid UpIntegrity
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewUpIntegrityFromValue(v string) (*UpIntegrity, error) {
	ev := UpIntegrity(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for UpIntegrity: valid values are %v", v, AllowedUpIntegrityEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v UpIntegrity) IsValid() bool {
	for _, existing := range AllowedUpIntegrityEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to UpIntegrity value
func (v UpIntegrity) Ptr() *UpIntegrity {
	return &v
}

type NullableUpIntegrity struct {
	value *UpIntegrity
	isSet bool
}

func (v NullableUpIntegrity) Get() *UpIntegrity {
	return v.value
}

func (v *NullableUpIntegrity) Set(val *UpIntegrity) {
	v.value = val
	v.isSet = true
}

func (v NullableUpIntegrity) IsSet() bool {
	return v.isSet
}

func (v *NullableUpIntegrity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpIntegrity(val *UpIntegrity) *NullableUpIntegrity {
	return &NullableUpIntegrity{value: val, isSet: true}
}

func (v NullableUpIntegrity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpIntegrity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
