// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

SMF PDU Session Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nsmf_PDUSession

import (
	"encoding/json"
	"fmt"
)

// ResourceStatus Status of SM context or PDU session resource. Possible values are - RELEASED - UNCHANGED - TRANSFERRED - UPDATED - ALT_ANCHOR_SMF
type ResourceStatus string

// List of ResourceStatus
const (
	RESOURCESTATUS_RELEASED       ResourceStatus = "RELEASED"
	RESOURCESTATUS_UNCHANGED      ResourceStatus = "UNCHANGED"
	RESOURCESTATUS_TRANSFERRED    ResourceStatus = "TRANSFERRED"
	RESOURCESTATUS_UPDATED        ResourceStatus = "UPDATED"
	RESOURCESTATUS_ALT_ANCHOR_SMF ResourceStatus = "ALT_ANCHOR_SMF"
)

// All allowed values of ResourceStatus enum
var AllowedResourceStatusEnumValues = []ResourceStatus{
	"RELEASED",
	"UNCHANGED",
	"TRANSFERRED",
	"UPDATED",
	"ALT_ANCHOR_SMF",
}

func (v *ResourceStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ResourceStatus(value)
	for _, existing := range AllowedResourceStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ResourceStatus", value)
}

// NewResourceStatusFromValue returns a pointer to a valid ResourceStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewResourceStatusFromValue(v string) (*ResourceStatus, error) {
	ev := ResourceStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ResourceStatus: valid values are %v", v, AllowedResourceStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ResourceStatus) IsValid() bool {
	for _, existing := range AllowedResourceStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ResourceStatus value
func (v ResourceStatus) Ptr() *ResourceStatus {
	return &v
}

type NullableResourceStatus struct {
	value *ResourceStatus
	isSet bool
}

func (v NullableResourceStatus) Get() *ResourceStatus {
	return v.value
}

func (v *NullableResourceStatus) Set(val *ResourceStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceStatus(val *ResourceStatus) *NullableResourceStatus {
	return &NullableResourceStatus{value: val, isSet: true}
}

func (v NullableResourceStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
