// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

SMF PDU Session Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nsmf_PDUSession

import (
	"encoding/json"
	"fmt"
)

// PsaIndication Indication of whether a PSA is inserted or removed. Possible values are   - PSA_INSERTED   - PSA_REMOVED   - PSA_INSERTED_ONLY   - PSA_REMOVED_ONLY
type PsaIndication struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *PsaIndication) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(PsaIndication)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *PsaIndication) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}

type NullablePsaIndication struct {
	value *PsaIndication
	isSet bool
}

func (v NullablePsaIndication) Get() *PsaIndication {
	return v.value
}

func (v *NullablePsaIndication) Set(val *PsaIndication) {
	v.value = val
	v.isSet = true
}

func (v NullablePsaIndication) IsSet() bool {
	return v.isSet
}

func (v *NullablePsaIndication) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePsaIndication(val *PsaIndication) *NullablePsaIndication {
	return &NullablePsaIndication{value: val, isSet: true}
}

func (v NullablePsaIndication) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePsaIndication) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
