// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

SMF PDU Session Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nsmf_PDUSession

import (
	"encoding/json"
)

// checks if the NgRanTargetId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NgRanTargetId{}

// NgRanTargetId Indicates a NG RAN as target of the handover
type NgRanTargetId struct {
	RanNodeId            NullableGlobalRanNodeId `json:"ranNodeId"`
	Tai                  Tai                     `json:"tai"`
	AdditionalProperties map[string]interface{}
}

type _NgRanTargetId NgRanTargetId

// NewNgRanTargetId instantiates a new NgRanTargetId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNgRanTargetId(ranNodeId NullableGlobalRanNodeId, tai Tai) *NgRanTargetId {
	this := NgRanTargetId{}
	this.RanNodeId = ranNodeId
	this.Tai = tai
	return &this
}

// NewNgRanTargetIdWithDefaults instantiates a new NgRanTargetId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNgRanTargetIdWithDefaults() *NgRanTargetId {
	this := NgRanTargetId{}
	return &this
}

// GetRanNodeId returns the RanNodeId field value
// If the value is explicit nil, the zero value for GlobalRanNodeId will be returned
func (o *NgRanTargetId) GetRanNodeId() GlobalRanNodeId {
	if o == nil || o.RanNodeId.Get() == nil {
		var ret GlobalRanNodeId
		return ret
	}

	return *o.RanNodeId.Get()
}

// GetRanNodeIdOk returns a tuple with the RanNodeId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NgRanTargetId) GetRanNodeIdOk() (*GlobalRanNodeId, bool) {
	if o == nil {
		return nil, false
	}
	return o.RanNodeId.Get(), o.RanNodeId.IsSet()
}

// SetRanNodeId sets field value
func (o *NgRanTargetId) SetRanNodeId(v GlobalRanNodeId) {
	o.RanNodeId.Set(&v)
}

// GetTai returns the Tai field value
func (o *NgRanTargetId) GetTai() Tai {
	if o == nil {
		var ret Tai
		return ret
	}

	return o.Tai
}

// GetTaiOk returns a tuple with the Tai field value
// and a boolean to check if the value has been set.
func (o *NgRanTargetId) GetTaiOk() (*Tai, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tai, true
}

// SetTai sets field value
func (o *NgRanTargetId) SetTai(v Tai) {
	o.Tai = v
}

func (o NgRanTargetId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ranNodeId"] = o.RanNodeId.Get()
	toSerialize["tai"] = o.Tai

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableNgRanTargetId struct {
	value *NgRanTargetId
	isSet bool
}

func (v NullableNgRanTargetId) Get() *NgRanTargetId {
	return v.value
}

func (v *NullableNgRanTargetId) Set(val *NgRanTargetId) {
	v.value = val
	v.isSet = true
}

func (v NullableNgRanTargetId) IsSet() bool {
	return v.isSet
}

func (v *NullableNgRanTargetId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNgRanTargetId(val *NgRanTargetId) *NullableNgRanTargetId {
	return &NullableNgRanTargetId{value: val, isSet: true}
}

func (v NullableNgRanTargetId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNgRanTargetId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
