// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

SMF PDU Session Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nsmf_PDUSession

import (
	"encoding/json"
)

// checks if the ServerAddressingInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerAddressingInfo{}

// ServerAddressingInfo Contains addressing information (IP addresses and/or FQDNs) of a server.
type ServerAddressingInfo struct {
	Ipv4Addresses        []string
	Ipv6Addresses        []Ipv6Addr
	FqdnList             []string
	AdditionalProperties map[string]interface{}
}

type _ServerAddressingInfo ServerAddressingInfo

// NewServerAddressingInfo instantiates a new ServerAddressingInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerAddressingInfo() *ServerAddressingInfo {
	this := ServerAddressingInfo{}
	return &this
}

// NewServerAddressingInfoWithDefaults instantiates a new ServerAddressingInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerAddressingInfoWithDefaults() *ServerAddressingInfo {
	this := ServerAddressingInfo{}
	return &this
}

// GetIpv4Addresses returns the Ipv4Addresses field value if set, zero value otherwise.
func (o *ServerAddressingInfo) GetIpv4Addresses() []string {
	if o == nil || IsNil(o.Ipv4Addresses) {
		var ret []string
		return ret
	}
	return o.Ipv4Addresses
}

// GetIpv4AddressesOk returns a tuple with the Ipv4Addresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerAddressingInfo) GetIpv4AddressesOk() ([]string, bool) {
	if o == nil || IsNil(o.Ipv4Addresses) {
		return nil, false
	}
	return o.Ipv4Addresses, true
}

// HasIpv4Addresses returns a boolean if a field has been set.
func (o *ServerAddressingInfo) HasIpv4Addresses() bool {
	if o != nil && !IsNil(o.Ipv4Addresses) {
		return true
	}

	return false
}

// SetIpv4Addresses gets a reference to the given []string and assigns it to the Ipv4Addresses field.
func (o *ServerAddressingInfo) SetIpv4Addresses(v []string) {
	o.Ipv4Addresses = v
}

// GetIpv6Addresses returns the Ipv6Addresses field value if set, zero value otherwise.
func (o *ServerAddressingInfo) GetIpv6Addresses() []Ipv6Addr {
	if o == nil || IsNil(o.Ipv6Addresses) {
		var ret []Ipv6Addr
		return ret
	}
	return o.Ipv6Addresses
}

// GetIpv6AddressesOk returns a tuple with the Ipv6Addresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerAddressingInfo) GetIpv6AddressesOk() ([]Ipv6Addr, bool) {
	if o == nil || IsNil(o.Ipv6Addresses) {
		return nil, false
	}
	return o.Ipv6Addresses, true
}

// HasIpv6Addresses returns a boolean if a field has been set.
func (o *ServerAddressingInfo) HasIpv6Addresses() bool {
	if o != nil && !IsNil(o.Ipv6Addresses) {
		return true
	}

	return false
}

// SetIpv6Addresses gets a reference to the given []Ipv6Addr and assigns it to the Ipv6Addresses field.
func (o *ServerAddressingInfo) SetIpv6Addresses(v []Ipv6Addr) {
	o.Ipv6Addresses = v
}

// GetFqdnList returns the FqdnList field value if set, zero value otherwise.
func (o *ServerAddressingInfo) GetFqdnList() []string {
	if o == nil || IsNil(o.FqdnList) {
		var ret []string
		return ret
	}
	return o.FqdnList
}

// GetFqdnListOk returns a tuple with the FqdnList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerAddressingInfo) GetFqdnListOk() ([]string, bool) {
	if o == nil || IsNil(o.FqdnList) {
		return nil, false
	}
	return o.FqdnList, true
}

// HasFqdnList returns a boolean if a field has been set.
func (o *ServerAddressingInfo) HasFqdnList() bool {
	if o != nil && !IsNil(o.FqdnList) {
		return true
	}

	return false
}

// SetFqdnList gets a reference to the given []string and assigns it to the FqdnList field.
func (o *ServerAddressingInfo) SetFqdnList(v []string) {
	o.FqdnList = v
}

func (o ServerAddressingInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ipv4Addresses) {
		toSerialize["ipv4Addresses"] = o.Ipv4Addresses
	}
	if !IsNil(o.Ipv6Addresses) {
		toSerialize["ipv6Addresses"] = o.Ipv6Addresses
	}
	if !IsNil(o.FqdnList) {
		toSerialize["fqdnList"] = o.FqdnList
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableServerAddressingInfo struct {
	value *ServerAddressingInfo
	isSet bool
}

func (v NullableServerAddressingInfo) Get() *ServerAddressingInfo {
	return v.value
}

func (v *NullableServerAddressingInfo) Set(val *ServerAddressingInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableServerAddressingInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableServerAddressingInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerAddressingInfo(val *ServerAddressingInfo) *NullableServerAddressingInfo {
	return &NullableServerAddressingInfo{value: val, isSet: true}
}

func (v NullableServerAddressingInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerAddressingInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
