// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

SMF PDU Session Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nsmf_PDUSession

import (
	"encoding/json"
)

// checks if the SmContextRetrieveData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SmContextRetrieveData{}

// SmContextRetrieveData Data within Retrieve SM Context Request
type SmContextRetrieveData struct {
	TargetMmeCap         *MmeCapabilities `json:"targetMmeCap,omitempty"`
	SmContextType        *SmContextType   `json:"smContextType,omitempty"`
	ServingNetwork       *PlmnId          `json:"servingNetwork,omitempty"`
	NotToTransferEbiList []int32          `json:"notToTransferEbiList,omitempty"`
	RanUnchangedInd      *bool            `json:"ranUnchangedInd,omitempty"`
	HrsboSupportInd      *bool            `json:"hrsboSupportInd,omitempty"`
	StoredOffloadIds     []string         `json:"storedOffloadIds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SmContextRetrieveData SmContextRetrieveData

// NewSmContextRetrieveData instantiates a new SmContextRetrieveData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSmContextRetrieveData() *SmContextRetrieveData {
	this := SmContextRetrieveData{}
	var ranUnchangedInd bool = false
	this.RanUnchangedInd = &ranUnchangedInd
	var hrsboSupportInd bool = false
	this.HrsboSupportInd = &hrsboSupportInd
	return &this
}

// NewSmContextRetrieveDataWithDefaults instantiates a new SmContextRetrieveData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSmContextRetrieveDataWithDefaults() *SmContextRetrieveData {
	this := SmContextRetrieveData{}
	var ranUnchangedInd bool = false
	this.RanUnchangedInd = &ranUnchangedInd
	var hrsboSupportInd bool = false
	this.HrsboSupportInd = &hrsboSupportInd
	return &this
}

// GetTargetMmeCap returns the TargetMmeCap field value if set, zero value otherwise.
func (o *SmContextRetrieveData) GetTargetMmeCap() MmeCapabilities {
	if o == nil || IsNil(o.TargetMmeCap) {
		var ret MmeCapabilities
		return ret
	}
	return *o.TargetMmeCap
}

// GetTargetMmeCapOk returns a tuple with the TargetMmeCap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmContextRetrieveData) GetTargetMmeCapOk() (*MmeCapabilities, bool) {
	if o == nil || IsNil(o.TargetMmeCap) {
		return nil, false
	}
	return o.TargetMmeCap, true
}

// HasTargetMmeCap returns a boolean if a field has been set.
func (o *SmContextRetrieveData) HasTargetMmeCap() bool {
	if o != nil && !IsNil(o.TargetMmeCap) {
		return true
	}

	return false
}

// SetTargetMmeCap gets a reference to the given MmeCapabilities and assigns it to the TargetMmeCap field.
func (o *SmContextRetrieveData) SetTargetMmeCap(v MmeCapabilities) {
	o.TargetMmeCap = &v
}

// GetSmContextType returns the SmContextType field value if set, zero value otherwise.
func (o *SmContextRetrieveData) GetSmContextType() SmContextType {
	if o == nil || IsNil(o.SmContextType) {
		var ret SmContextType
		return ret
	}
	return *o.SmContextType
}

// GetSmContextTypeOk returns a tuple with the SmContextType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmContextRetrieveData) GetSmContextTypeOk() (*SmContextType, bool) {
	if o == nil || IsNil(o.SmContextType) {
		return nil, false
	}
	return o.SmContextType, true
}

// HasSmContextType returns a boolean if a field has been set.
func (o *SmContextRetrieveData) HasSmContextType() bool {
	if o != nil && !IsNil(o.SmContextType) {
		return true
	}

	return false
}

// SetSmContextType gets a reference to the given SmContextType and assigns it to the SmContextType field.
func (o *SmContextRetrieveData) SetSmContextType(v SmContextType) {
	o.SmContextType = &v
}

// GetServingNetwork returns the ServingNetwork field value if set, zero value otherwise.
func (o *SmContextRetrieveData) GetServingNetwork() PlmnId {
	if o == nil || IsNil(o.ServingNetwork) {
		var ret PlmnId
		return ret
	}
	return *o.ServingNetwork
}

// GetServingNetworkOk returns a tuple with the ServingNetwork field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmContextRetrieveData) GetServingNetworkOk() (*PlmnId, bool) {
	if o == nil || IsNil(o.ServingNetwork) {
		return nil, false
	}
	return o.ServingNetwork, true
}

// HasServingNetwork returns a boolean if a field has been set.
func (o *SmContextRetrieveData) HasServingNetwork() bool {
	if o != nil && !IsNil(o.ServingNetwork) {
		return true
	}

	return false
}

// SetServingNetwork gets a reference to the given PlmnId and assigns it to the ServingNetwork field.
func (o *SmContextRetrieveData) SetServingNetwork(v PlmnId) {
	o.ServingNetwork = &v
}

// GetNotToTransferEbiList returns the NotToTransferEbiList field value if set, zero value otherwise.
func (o *SmContextRetrieveData) GetNotToTransferEbiList() []int32 {
	if o == nil || IsNil(o.NotToTransferEbiList) {
		var ret []int32
		return ret
	}
	return o.NotToTransferEbiList
}

// GetNotToTransferEbiListOk returns a tuple with the NotToTransferEbiList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmContextRetrieveData) GetNotToTransferEbiListOk() ([]int32, bool) {
	if o == nil || IsNil(o.NotToTransferEbiList) {
		return nil, false
	}
	return o.NotToTransferEbiList, true
}

// HasNotToTransferEbiList returns a boolean if a field has been set.
func (o *SmContextRetrieveData) HasNotToTransferEbiList() bool {
	if o != nil && !IsNil(o.NotToTransferEbiList) {
		return true
	}

	return false
}

// SetNotToTransferEbiList gets a reference to the given []int32 and assigns it to the NotToTransferEbiList field.
func (o *SmContextRetrieveData) SetNotToTransferEbiList(v []int32) {
	o.NotToTransferEbiList = v
}

// GetRanUnchangedInd returns the RanUnchangedInd field value if set, zero value otherwise.
func (o *SmContextRetrieveData) GetRanUnchangedInd() bool {
	if o == nil || IsNil(o.RanUnchangedInd) {
		var ret bool
		return ret
	}
	return *o.RanUnchangedInd
}

// GetRanUnchangedIndOk returns a tuple with the RanUnchangedInd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmContextRetrieveData) GetRanUnchangedIndOk() (*bool, bool) {
	if o == nil || IsNil(o.RanUnchangedInd) {
		return nil, false
	}
	return o.RanUnchangedInd, true
}

// HasRanUnchangedInd returns a boolean if a field has been set.
func (o *SmContextRetrieveData) HasRanUnchangedInd() bool {
	if o != nil && !IsNil(o.RanUnchangedInd) {
		return true
	}

	return false
}

// SetRanUnchangedInd gets a reference to the given bool and assigns it to the RanUnchangedInd field.
func (o *SmContextRetrieveData) SetRanUnchangedInd(v bool) {
	o.RanUnchangedInd = &v
}

// GetHrsboSupportInd returns the HrsboSupportInd field value if set, zero value otherwise.
func (o *SmContextRetrieveData) GetHrsboSupportInd() bool {
	if o == nil || IsNil(o.HrsboSupportInd) {
		var ret bool
		return ret
	}
	return *o.HrsboSupportInd
}

// GetHrsboSupportIndOk returns a tuple with the HrsboSupportInd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmContextRetrieveData) GetHrsboSupportIndOk() (*bool, bool) {
	if o == nil || IsNil(o.HrsboSupportInd) {
		return nil, false
	}
	return o.HrsboSupportInd, true
}

// HasHrsboSupportInd returns a boolean if a field has been set.
func (o *SmContextRetrieveData) HasHrsboSupportInd() bool {
	if o != nil && !IsNil(o.HrsboSupportInd) {
		return true
	}

	return false
}

// SetHrsboSupportInd gets a reference to the given bool and assigns it to the HrsboSupportInd field.
func (o *SmContextRetrieveData) SetHrsboSupportInd(v bool) {
	o.HrsboSupportInd = &v
}

// GetStoredOffloadIds returns the StoredOffloadIds field value if set, zero value otherwise.
func (o *SmContextRetrieveData) GetStoredOffloadIds() []string {
	if o == nil || IsNil(o.StoredOffloadIds) {
		var ret []string
		return ret
	}
	return o.StoredOffloadIds
}

// GetStoredOffloadIdsOk returns a tuple with the StoredOffloadIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmContextRetrieveData) GetStoredOffloadIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.StoredOffloadIds) {
		return nil, false
	}
	return o.StoredOffloadIds, true
}

// HasStoredOffloadIds returns a boolean if a field has been set.
func (o *SmContextRetrieveData) HasStoredOffloadIds() bool {
	if o != nil && !IsNil(o.StoredOffloadIds) {
		return true
	}

	return false
}

// SetStoredOffloadIds gets a reference to the given []string and assigns it to the StoredOffloadIds field.
func (o *SmContextRetrieveData) SetStoredOffloadIds(v []string) {
	o.StoredOffloadIds = v
}

func (o SmContextRetrieveData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TargetMmeCap) {
		toSerialize["targetMmeCap"] = o.TargetMmeCap
	}
	if !IsNil(o.SmContextType) {
		toSerialize["smContextType"] = o.SmContextType
	}
	if !IsNil(o.ServingNetwork) {
		toSerialize["servingNetwork"] = o.ServingNetwork
	}
	if !IsNil(o.NotToTransferEbiList) {
		toSerialize["notToTransferEbiList"] = o.NotToTransferEbiList
	}
	if !IsNil(o.RanUnchangedInd) {
		toSerialize["ranUnchangedInd"] = o.RanUnchangedInd
	}
	if !IsNil(o.HrsboSupportInd) {
		toSerialize["hrsboSupportInd"] = o.HrsboSupportInd
	}
	if !IsNil(o.StoredOffloadIds) {
		toSerialize["storedOffloadIds"] = o.StoredOffloadIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableSmContextRetrieveData struct {
	value *SmContextRetrieveData
	isSet bool
}

func (v NullableSmContextRetrieveData) Get() *SmContextRetrieveData {
	return v.value
}

func (v *NullableSmContextRetrieveData) Set(val *SmContextRetrieveData) {
	v.value = val
	v.isSet = true
}

func (v NullableSmContextRetrieveData) IsSet() bool {
	return v.isSet
}

func (v *NullableSmContextRetrieveData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmContextRetrieveData(val *SmContextRetrieveData) *NullableSmContextRetrieveData {
	return &NullableSmContextRetrieveData{value: val, isSet: true}
}

func (v NullableSmContextRetrieveData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmContextRetrieveData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
