// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

SMF PDU Session Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nsmf_PDUSession

import (
	"encoding/json"
)

// checks if the TrafficInfluenceInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrafficInfluenceInfo{}

// TrafficInfluenceInfo Traffic influence information applicable at the VPLMN for an HR-SBO PDU session
type TrafficInfluenceInfo struct {
	TrafficInfluData []TrafficInfluenceData `json:"trafficInfluData,omitempty"`
	// Map of Traffic Control data policy decisions. The key used in this map for each entry is the tcId attribute of the corresponding TrafficControlData.
	TraffContDecs        *map[string]TrafficControlData `json:"traffContDecs,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TrafficInfluenceInfo TrafficInfluenceInfo

// NewTrafficInfluenceInfo instantiates a new TrafficInfluenceInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrafficInfluenceInfo() *TrafficInfluenceInfo {
	this := TrafficInfluenceInfo{}
	return &this
}

// NewTrafficInfluenceInfoWithDefaults instantiates a new TrafficInfluenceInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrafficInfluenceInfoWithDefaults() *TrafficInfluenceInfo {
	this := TrafficInfluenceInfo{}
	return &this
}

// GetTrafficInfluData returns the TrafficInfluData field value if set, zero value otherwise.
func (o *TrafficInfluenceInfo) GetTrafficInfluData() []TrafficInfluenceData {
	if o == nil || IsNil(o.TrafficInfluData) {
		var ret []TrafficInfluenceData
		return ret
	}
	return o.TrafficInfluData
}

// GetTrafficInfluDataOk returns a tuple with the TrafficInfluData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficInfluenceInfo) GetTrafficInfluDataOk() ([]TrafficInfluenceData, bool) {
	if o == nil || IsNil(o.TrafficInfluData) {
		return nil, false
	}
	return o.TrafficInfluData, true
}

// HasTrafficInfluData returns a boolean if a field has been set.
func (o *TrafficInfluenceInfo) HasTrafficInfluData() bool {
	if o != nil && !IsNil(o.TrafficInfluData) {
		return true
	}

	return false
}

// SetTrafficInfluData gets a reference to the given []TrafficInfluenceData and assigns it to the TrafficInfluData field.
func (o *TrafficInfluenceInfo) SetTrafficInfluData(v []TrafficInfluenceData) {
	o.TrafficInfluData = v
}

// GetTraffContDecs returns the TraffContDecs field value if set, zero value otherwise.
func (o *TrafficInfluenceInfo) GetTraffContDecs() map[string]TrafficControlData {
	if o == nil || IsNil(o.TraffContDecs) {
		var ret map[string]TrafficControlData
		return ret
	}
	return *o.TraffContDecs
}

// GetTraffContDecsOk returns a tuple with the TraffContDecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficInfluenceInfo) GetTraffContDecsOk() (*map[string]TrafficControlData, bool) {
	if o == nil || IsNil(o.TraffContDecs) {
		return nil, false
	}
	return o.TraffContDecs, true
}

// HasTraffContDecs returns a boolean if a field has been set.
func (o *TrafficInfluenceInfo) HasTraffContDecs() bool {
	if o != nil && !IsNil(o.TraffContDecs) {
		return true
	}

	return false
}

// SetTraffContDecs gets a reference to the given map[string]TrafficControlData and assigns it to the TraffContDecs field.
func (o *TrafficInfluenceInfo) SetTraffContDecs(v map[string]TrafficControlData) {
	o.TraffContDecs = &v
}

func (o TrafficInfluenceInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TrafficInfluData) {
		toSerialize["trafficInfluData"] = o.TrafficInfluData
	}
	if !IsNil(o.TraffContDecs) {
		toSerialize["traffContDecs"] = o.TraffContDecs
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableTrafficInfluenceInfo struct {
	value *TrafficInfluenceInfo
	isSet bool
}

func (v NullableTrafficInfluenceInfo) Get() *TrafficInfluenceInfo {
	return v.value
}

func (v *NullableTrafficInfluenceInfo) Set(val *TrafficInfluenceInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableTrafficInfluenceInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableTrafficInfluenceInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrafficInfluenceInfo(val *TrafficInfluenceInfo) *NullableTrafficInfluenceInfo {
	return &NullableTrafficInfluenceInfo{value: val, isSet: true}
}

func (v NullableTrafficInfluenceInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrafficInfluenceInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
