// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

SMF PDU Session Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nsmf_PDUSession

import (
	"encoding/json"
)

// checks if the PointAltitudeUncertainty type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PointAltitudeUncertainty{}

// PointAltitudeUncertainty Ellipsoid point with altitude and uncertainty ellipsoid.
type PointAltitudeUncertainty struct {
	GADShape
	Point *GeographicalCoordinates `json:"point,omitempty"`
	// Indicates value of altitude.
	Altitude           *float64            `json:"altitude,omitempty"`
	UncertaintyEllipse *UncertaintyEllipse `json:"uncertaintyEllipse,omitempty"`
	// Indicates value of uncertainty.
	UncertaintyAltitude *float32 `json:"uncertaintyAltitude,omitempty"`
	// Indicates value of confidence.
	Confidence *int32 `json:"confidence,omitempty"`
	// Indicates value of confidence.
	VConfidence          *int32 `json:"vConfidence,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PointAltitudeUncertainty PointAltitudeUncertainty

// NewPointAltitudeUncertainty instantiates a new PointAltitudeUncertainty object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPointAltitudeUncertainty(shape SupportedGADShapes) *PointAltitudeUncertainty {
	this := PointAltitudeUncertainty{}
	this.Shape = shape
	return &this
}

// NewPointAltitudeUncertaintyWithDefaults instantiates a new PointAltitudeUncertainty object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPointAltitudeUncertaintyWithDefaults() *PointAltitudeUncertainty {
	this := PointAltitudeUncertainty{}
	return &this
}

// GetPoint returns the Point field value if set, zero value otherwise.
func (o *PointAltitudeUncertainty) GetPoint() GeographicalCoordinates {
	if o == nil || IsNil(o.Point) {
		var ret GeographicalCoordinates
		return ret
	}
	return *o.Point
}

// GetPointOk returns a tuple with the Point field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointAltitudeUncertainty) GetPointOk() (*GeographicalCoordinates, bool) {
	if o == nil || IsNil(o.Point) {
		return nil, false
	}
	return o.Point, true
}

// HasPoint returns a boolean if a field has been set.
func (o *PointAltitudeUncertainty) HasPoint() bool {
	if o != nil && !IsNil(o.Point) {
		return true
	}

	return false
}

// SetPoint gets a reference to the given GeographicalCoordinates and assigns it to the Point field.
func (o *PointAltitudeUncertainty) SetPoint(v GeographicalCoordinates) {
	o.Point = &v
}

// GetAltitude returns the Altitude field value if set, zero value otherwise.
func (o *PointAltitudeUncertainty) GetAltitude() float64 {
	if o == nil || IsNil(o.Altitude) {
		var ret float64
		return ret
	}
	return *o.Altitude
}

// GetAltitudeOk returns a tuple with the Altitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointAltitudeUncertainty) GetAltitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Altitude) {
		return nil, false
	}
	return o.Altitude, true
}

// HasAltitude returns a boolean if a field has been set.
func (o *PointAltitudeUncertainty) HasAltitude() bool {
	if o != nil && !IsNil(o.Altitude) {
		return true
	}

	return false
}

// SetAltitude gets a reference to the given float64 and assigns it to the Altitude field.
func (o *PointAltitudeUncertainty) SetAltitude(v float64) {
	o.Altitude = &v
}

// GetUncertaintyEllipse returns the UncertaintyEllipse field value if set, zero value otherwise.
func (o *PointAltitudeUncertainty) GetUncertaintyEllipse() UncertaintyEllipse {
	if o == nil || IsNil(o.UncertaintyEllipse) {
		var ret UncertaintyEllipse
		return ret
	}
	return *o.UncertaintyEllipse
}

// GetUncertaintyEllipseOk returns a tuple with the UncertaintyEllipse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointAltitudeUncertainty) GetUncertaintyEllipseOk() (*UncertaintyEllipse, bool) {
	if o == nil || IsNil(o.UncertaintyEllipse) {
		return nil, false
	}
	return o.UncertaintyEllipse, true
}

// HasUncertaintyEllipse returns a boolean if a field has been set.
func (o *PointAltitudeUncertainty) HasUncertaintyEllipse() bool {
	if o != nil && !IsNil(o.UncertaintyEllipse) {
		return true
	}

	return false
}

// SetUncertaintyEllipse gets a reference to the given UncertaintyEllipse and assigns it to the UncertaintyEllipse field.
func (o *PointAltitudeUncertainty) SetUncertaintyEllipse(v UncertaintyEllipse) {
	o.UncertaintyEllipse = &v
}

// GetUncertaintyAltitude returns the UncertaintyAltitude field value if set, zero value otherwise.
func (o *PointAltitudeUncertainty) GetUncertaintyAltitude() float32 {
	if o == nil || IsNil(o.UncertaintyAltitude) {
		var ret float32
		return ret
	}
	return *o.UncertaintyAltitude
}

// GetUncertaintyAltitudeOk returns a tuple with the UncertaintyAltitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointAltitudeUncertainty) GetUncertaintyAltitudeOk() (*float32, bool) {
	if o == nil || IsNil(o.UncertaintyAltitude) {
		return nil, false
	}
	return o.UncertaintyAltitude, true
}

// HasUncertaintyAltitude returns a boolean if a field has been set.
func (o *PointAltitudeUncertainty) HasUncertaintyAltitude() bool {
	if o != nil && !IsNil(o.UncertaintyAltitude) {
		return true
	}

	return false
}

// SetUncertaintyAltitude gets a reference to the given float32 and assigns it to the UncertaintyAltitude field.
func (o *PointAltitudeUncertainty) SetUncertaintyAltitude(v float32) {
	o.UncertaintyAltitude = &v
}

// GetConfidence returns the Confidence field value if set, zero value otherwise.
func (o *PointAltitudeUncertainty) GetConfidence() int32 {
	if o == nil || IsNil(o.Confidence) {
		var ret int32
		return ret
	}
	return *o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointAltitudeUncertainty) GetConfidenceOk() (*int32, bool) {
	if o == nil || IsNil(o.Confidence) {
		return nil, false
	}
	return o.Confidence, true
}

// HasConfidence returns a boolean if a field has been set.
func (o *PointAltitudeUncertainty) HasConfidence() bool {
	if o != nil && !IsNil(o.Confidence) {
		return true
	}

	return false
}

// SetConfidence gets a reference to the given int32 and assigns it to the Confidence field.
func (o *PointAltitudeUncertainty) SetConfidence(v int32) {
	o.Confidence = &v
}

// GetVConfidence returns the VConfidence field value if set, zero value otherwise.
func (o *PointAltitudeUncertainty) GetVConfidence() int32 {
	if o == nil || IsNil(o.VConfidence) {
		var ret int32
		return ret
	}
	return *o.VConfidence
}

// GetVConfidenceOk returns a tuple with the VConfidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointAltitudeUncertainty) GetVConfidenceOk() (*int32, bool) {
	if o == nil || IsNil(o.VConfidence) {
		return nil, false
	}
	return o.VConfidence, true
}

// HasVConfidence returns a boolean if a field has been set.
func (o *PointAltitudeUncertainty) HasVConfidence() bool {
	if o != nil && !IsNil(o.VConfidence) {
		return true
	}

	return false
}

// SetVConfidence gets a reference to the given int32 and assigns it to the VConfidence field.
func (o *PointAltitudeUncertainty) SetVConfidence(v int32) {
	o.VConfidence = &v
}

func (o PointAltitudeUncertainty) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedGADShape, errGADShape := json.Marshal(o.GADShape)
	if errGADShape != nil {
		return map[string]interface{}{}, errGADShape
	}
	errGADShape = json.Unmarshal([]byte(serializedGADShape), &toSerialize)
	if errGADShape != nil {
		return map[string]interface{}{}, errGADShape
	}
	if !IsNil(o.Point) {
		toSerialize["point"] = o.Point
	}
	if !IsNil(o.Altitude) {
		toSerialize["altitude"] = o.Altitude
	}
	if !IsNil(o.UncertaintyEllipse) {
		toSerialize["uncertaintyEllipse"] = o.UncertaintyEllipse
	}
	if !IsNil(o.UncertaintyAltitude) {
		toSerialize["uncertaintyAltitude"] = o.UncertaintyAltitude
	}
	if !IsNil(o.Confidence) {
		toSerialize["confidence"] = o.Confidence
	}
	if !IsNil(o.VConfidence) {
		toSerialize["vConfidence"] = o.VConfidence
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullablePointAltitudeUncertainty struct {
	value *PointAltitudeUncertainty
	isSet bool
}

func (v NullablePointAltitudeUncertainty) Get() *PointAltitudeUncertainty {
	return v.value
}

func (v *NullablePointAltitudeUncertainty) Set(val *PointAltitudeUncertainty) {
	v.value = val
	v.isSet = true
}

func (v NullablePointAltitudeUncertainty) IsSet() bool {
	return v.isSet
}

func (v *NullablePointAltitudeUncertainty) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePointAltitudeUncertainty(val *PointAltitudeUncertainty) *NullablePointAltitudeUncertainty {
	return &NullablePointAltitudeUncertainty{value: val, isSet: true}
}

func (v NullablePointAltitudeUncertainty) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePointAltitudeUncertainty) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
