// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

SMF PDU Session Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nsmf_PDUSession

import (
	"encoding/json"
	"fmt"
)

// NotificationCause Cause for generating a notification. Possible values are - QOS_FULFILLED - QOS_NOT_FULFILLED - UP_SEC_FULFILLED - UP_SEC_NOT_FULFILLED
type NotificationCause string

// List of NotificationCause
const (
	NOTIFICATIONCAUSE_QOS_FULFILLED        NotificationCause = "QOS_FULFILLED"
	NOTIFICATIONCAUSE_QOS_NOT_FULFILLED    NotificationCause = "QOS_NOT_FULFILLED"
	NOTIFICATIONCAUSE_UP_SEC_FULFILLED     NotificationCause = "UP_SEC_FULFILLED"
	NOTIFICATIONCAUSE_UP_SEC_NOT_FULFILLED NotificationCause = "UP_SEC_NOT_FULFILLED"
)

// All allowed values of NotificationCause enum
var AllowedNotificationCauseEnumValues = []NotificationCause{
	"QOS_FULFILLED",
	"QOS_NOT_FULFILLED",
	"UP_SEC_FULFILLED",
	"UP_SEC_NOT_FULFILLED",
}

func (v *NotificationCause) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := NotificationCause(value)
	for _, existing := range AllowedNotificationCauseEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid NotificationCause", value)
}

// NewNotificationCauseFromValue returns a pointer to a valid NotificationCause
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewNotificationCauseFromValue(v string) (*NotificationCause, error) {
	ev := NotificationCause(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for NotificationCause: valid values are %v", v, AllowedNotificationCauseEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v NotificationCause) IsValid() bool {
	for _, existing := range AllowedNotificationCauseEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to NotificationCause value
func (v NotificationCause) Ptr() *NotificationCause {
	return &v
}

type NullableNotificationCause struct {
	value *NotificationCause
	isSet bool
}

func (v NullableNotificationCause) Get() *NotificationCause {
	return v.value
}

func (v *NullableNotificationCause) Set(val *NotificationCause) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationCause) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationCause) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationCause(val *NotificationCause) *NullableNotificationCause {
	return &NullableNotificationCause{value: val, isSet: true}
}

func (v NullableNotificationCause) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationCause) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
