// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
NRF NFDiscovery Service

Testing IndividualSCPDomainRoutingInformationSubscriptionDocumentAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Nnrf_NFDiscovery

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_Nnrf_NFDiscovery_IndividualSCPDomainRoutingInformationSubscriptionDocumentAPIService(t *testing.T) {

	configuration := NewConfiguration()
	apiClient := NewAPIClient(configuration)

	t.Run("Test IndividualSCPDomainRoutingInformationSubscriptionDocumentAPIService ScpDomainRoutingInfoUnsubscribe", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var subscriptionID string

		httpRes, err := apiClient.IndividualSCPDomainRoutingInformationSubscriptionDocumentAPI.ScpDomainRoutingInfoUnsubscribe(context.Background(), subscriptionID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

}
