// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
NRF NFDiscovery Service

Testing StoredSearchDocumentAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Nnrf_NFDiscovery

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_Nnrf_NFDiscovery_StoredSearchDocumentAPIService(t *testing.T) {

	configuration := NewConfiguration()
	apiClient := NewAPIClient(configuration)

	t.Run("Test StoredSearchDocumentAPIService RetrieveStoredSearch", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var searchId string

		resp, httpRes, err := apiClient.StoredSearchDocumentAPI.RetrieveStoredSearch(context.Background(), searchId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

}
