// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
NRF NFDiscovery Service

NRF NFDiscovery Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nnrf_NFDiscovery

import (
	"encoding/json"
)

// checks if the DnnSmfInfoItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DnnSmfInfoItem{}

// DnnSmfInfoItem Set of parameters supported by SMF for a given DNN
type DnnSmfInfoItem struct {
	Dnn                  DnnSmfInfoItemDnn             `json:"dnn"`
	DnaiList             []DnnSmfInfoItemDnaiListInner `json:"dnaiList,omitempty"`
	UePlmnRangeList      []PlmnRange                   `json:"uePlmnRangeList,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DnnSmfInfoItem DnnSmfInfoItem

// NewDnnSmfInfoItem instantiates a new DnnSmfInfoItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDnnSmfInfoItem(dnn DnnSmfInfoItemDnn) *DnnSmfInfoItem {
	this := DnnSmfInfoItem{}
	this.Dnn = dnn
	return &this
}

// NewDnnSmfInfoItemWithDefaults instantiates a new DnnSmfInfoItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDnnSmfInfoItemWithDefaults() *DnnSmfInfoItem {
	this := DnnSmfInfoItem{}
	return &this
}

// GetDnn returns the Dnn field value
func (o *DnnSmfInfoItem) GetDnn() DnnSmfInfoItemDnn {
	if o == nil {
		var ret DnnSmfInfoItemDnn
		return ret
	}

	return o.Dnn
}

// GetDnnOk returns a tuple with the Dnn field value
// and a boolean to check if the value has been set.
func (o *DnnSmfInfoItem) GetDnnOk() (*DnnSmfInfoItemDnn, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dnn, true
}

// SetDnn sets field value
func (o *DnnSmfInfoItem) SetDnn(v DnnSmfInfoItemDnn) {
	o.Dnn = v
}

// GetDnaiList returns the DnaiList field value if set, zero value otherwise.
func (o *DnnSmfInfoItem) GetDnaiList() []DnnSmfInfoItemDnaiListInner {
	if o == nil || IsNil(o.DnaiList) {
		var ret []DnnSmfInfoItemDnaiListInner
		return ret
	}
	return o.DnaiList
}

// GetDnaiListOk returns a tuple with the DnaiList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnnSmfInfoItem) GetDnaiListOk() ([]DnnSmfInfoItemDnaiListInner, bool) {
	if o == nil || IsNil(o.DnaiList) {
		return nil, false
	}
	return o.DnaiList, true
}

// HasDnaiList returns a boolean if a field has been set.
func (o *DnnSmfInfoItem) HasDnaiList() bool {
	if o != nil && !IsNil(o.DnaiList) {
		return true
	}

	return false
}

// SetDnaiList gets a reference to the given []DnnSmfInfoItemDnaiListInner and assigns it to the DnaiList field.
func (o *DnnSmfInfoItem) SetDnaiList(v []DnnSmfInfoItemDnaiListInner) {
	o.DnaiList = v
}

// GetUePlmnRangeList returns the UePlmnRangeList field value if set, zero value otherwise.
func (o *DnnSmfInfoItem) GetUePlmnRangeList() []PlmnRange {
	if o == nil || IsNil(o.UePlmnRangeList) {
		var ret []PlmnRange
		return ret
	}
	return o.UePlmnRangeList
}

// GetUePlmnRangeListOk returns a tuple with the UePlmnRangeList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnnSmfInfoItem) GetUePlmnRangeListOk() ([]PlmnRange, bool) {
	if o == nil || IsNil(o.UePlmnRangeList) {
		return nil, false
	}
	return o.UePlmnRangeList, true
}

// HasUePlmnRangeList returns a boolean if a field has been set.
func (o *DnnSmfInfoItem) HasUePlmnRangeList() bool {
	if o != nil && !IsNil(o.UePlmnRangeList) {
		return true
	}

	return false
}

// SetUePlmnRangeList gets a reference to the given []PlmnRange and assigns it to the UePlmnRangeList field.
func (o *DnnSmfInfoItem) SetUePlmnRangeList(v []PlmnRange) {
	o.UePlmnRangeList = v
}

func (o DnnSmfInfoItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dnn"] = o.Dnn
	if !IsNil(o.DnaiList) {
		toSerialize["dnaiList"] = o.DnaiList
	}
	if !IsNil(o.UePlmnRangeList) {
		toSerialize["uePlmnRangeList"] = o.UePlmnRangeList
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableDnnSmfInfoItem struct {
	value *DnnSmfInfoItem
	isSet bool
}

func (v NullableDnnSmfInfoItem) Get() *DnnSmfInfoItem {
	return v.value
}

func (v *NullableDnnSmfInfoItem) Set(val *DnnSmfInfoItem) {
	v.value = val
	v.isSet = true
}

func (v NullableDnnSmfInfoItem) IsSet() bool {
	return v.isSet
}

func (v *NullableDnnSmfInfoItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDnnSmfInfoItem(val *DnnSmfInfoItem) *NullableDnnSmfInfoItem {
	return &NullableDnnSmfInfoItem{value: val, isSet: true}
}

func (v NullableDnnSmfInfoItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDnnSmfInfoItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
