// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
NRF NFDiscovery Service

NRF NFDiscovery Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nnrf_NFDiscovery

import (
	"encoding/json"
	"fmt"
)

// ScpCapability Indicates the capabilities supported by an SCP
type ScpCapability string

// List of ScpCapability
const (
	SCPCAPABILITY_INDIRECT_COM_WITH_DELEG_DISC ScpCapability = "INDIRECT_COM_WITH_DELEG_DISC"
)

// All allowed values of ScpCapability enum
var AllowedScpCapabilityEnumValues = []ScpCapability{
	"INDIRECT_COM_WITH_DELEG_DISC",
}

func (v *ScpCapability) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ScpCapability(value)
	for _, existing := range AllowedScpCapabilityEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ScpCapability", value)
}

// NewScpCapabilityFromValue returns a pointer to a valid ScpCapability
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewScpCapabilityFromValue(v string) (*ScpCapability, error) {
	ev := ScpCapability(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ScpCapability: valid values are %v", v, AllowedScpCapabilityEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ScpCapability) IsValid() bool {
	for _, existing := range AllowedScpCapabilityEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ScpCapability value
func (v ScpCapability) Ptr() *ScpCapability {
	return &v
}

type NullableScpCapability struct {
	value *ScpCapability
	isSet bool
}

func (v NullableScpCapability) Get() *ScpCapability {
	return v.value
}

func (v *NullableScpCapability) Set(val *ScpCapability) {
	v.value = val
	v.isSet = true
}

func (v NullableScpCapability) IsSet() bool {
	return v.isSet
}

func (v *NullableScpCapability) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScpCapability(val *ScpCapability) *NullableScpCapability {
	return &NullableScpCapability{value: val, isSet: true}
}

func (v NullableScpCapability) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScpCapability) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
