// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
NRF NFDiscovery Service

NRF NFDiscovery Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nnrf_NFDiscovery

import (
	"encoding/json"
)

// checks if the NetworkNodeDiameterAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkNodeDiameterAddress{}

// NetworkNodeDiameterAddress This data type is a part of smsfDiameterAddress and it should be present whenever smsf supports Diameter protocol.
type NetworkNodeDiameterAddress struct {
	// Fully Qualified Domain Name
	Name string `json:"name" validate:"regexp=^([0-9A-Za-z]([-0-9A-Za-z]{0,61}[0-9A-Za-z])?\\\\.)+[A-Za-z]{2,63}\\\\.?$"`
	// Fully Qualified Domain Name
	Realm                string `json:"realm" validate:"regexp=^([0-9A-Za-z]([-0-9A-Za-z]{0,61}[0-9A-Za-z])?\\\\.)+[A-Za-z]{2,63}\\\\.?$"`
	AdditionalProperties map[string]interface{}
}

type _NetworkNodeDiameterAddress NetworkNodeDiameterAddress

// NewNetworkNodeDiameterAddress instantiates a new NetworkNodeDiameterAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkNodeDiameterAddress(name string, realm string) *NetworkNodeDiameterAddress {
	this := NetworkNodeDiameterAddress{}
	this.Name = name
	this.Realm = realm
	return &this
}

// NewNetworkNodeDiameterAddressWithDefaults instantiates a new NetworkNodeDiameterAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkNodeDiameterAddressWithDefaults() *NetworkNodeDiameterAddress {
	this := NetworkNodeDiameterAddress{}
	return &this
}

// GetName returns the Name field value
func (o *NetworkNodeDiameterAddress) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NetworkNodeDiameterAddress) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NetworkNodeDiameterAddress) SetName(v string) {
	o.Name = v
}

// GetRealm returns the Realm field value
func (o *NetworkNodeDiameterAddress) GetRealm() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Realm
}

// GetRealmOk returns a tuple with the Realm field value
// and a boolean to check if the value has been set.
func (o *NetworkNodeDiameterAddress) GetRealmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Realm, true
}

// SetRealm sets field value
func (o *NetworkNodeDiameterAddress) SetRealm(v string) {
	o.Realm = v
}

func (o NetworkNodeDiameterAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["realm"] = o.Realm

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableNetworkNodeDiameterAddress struct {
	value *NetworkNodeDiameterAddress
	isSet bool
}

func (v NullableNetworkNodeDiameterAddress) Get() *NetworkNodeDiameterAddress {
	return v.value
}

func (v *NullableNetworkNodeDiameterAddress) Set(val *NetworkNodeDiameterAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkNodeDiameterAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkNodeDiameterAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkNodeDiameterAddress(val *NetworkNodeDiameterAddress) *NullableNetworkNodeDiameterAddress {
	return &NullableNetworkNodeDiameterAddress{value: val, isSet: true}
}

func (v NullableNetworkNodeDiameterAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkNodeDiameterAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
