// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
NRF NFDiscovery Service

NRF NFDiscovery Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nnrf_NFDiscovery

import (
	"encoding/json"
)

// checks if the NoProfileMatchInfo1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NoProfileMatchInfo1{}

// NoProfileMatchInfo1 Provides the reason for not finding NF matching the search criteria
type NoProfileMatchInfo1 struct {
	Reason                    NoProfileMatchReason    `json:"reason"`
	QueryParamCombinationList []QueryParamCombination `json:"queryParamCombinationList,omitempty"`
	AdditionalProperties      map[string]interface{}
}

type _NoProfileMatchInfo1 NoProfileMatchInfo1

// NewNoProfileMatchInfo1 instantiates a new NoProfileMatchInfo1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNoProfileMatchInfo1(reason NoProfileMatchReason) *NoProfileMatchInfo1 {
	this := NoProfileMatchInfo1{}
	this.Reason = reason
	return &this
}

// NewNoProfileMatchInfo1WithDefaults instantiates a new NoProfileMatchInfo1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNoProfileMatchInfo1WithDefaults() *NoProfileMatchInfo1 {
	this := NoProfileMatchInfo1{}
	return &this
}

// GetReason returns the Reason field value
func (o *NoProfileMatchInfo1) GetReason() NoProfileMatchReason {
	if o == nil {
		var ret NoProfileMatchReason
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *NoProfileMatchInfo1) GetReasonOk() (*NoProfileMatchReason, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *NoProfileMatchInfo1) SetReason(v NoProfileMatchReason) {
	o.Reason = v
}

// GetQueryParamCombinationList returns the QueryParamCombinationList field value if set, zero value otherwise.
func (o *NoProfileMatchInfo1) GetQueryParamCombinationList() []QueryParamCombination {
	if o == nil || IsNil(o.QueryParamCombinationList) {
		var ret []QueryParamCombination
		return ret
	}
	return o.QueryParamCombinationList
}

// GetQueryParamCombinationListOk returns a tuple with the QueryParamCombinationList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NoProfileMatchInfo1) GetQueryParamCombinationListOk() ([]QueryParamCombination, bool) {
	if o == nil || IsNil(o.QueryParamCombinationList) {
		return nil, false
	}
	return o.QueryParamCombinationList, true
}

// HasQueryParamCombinationList returns a boolean if a field has been set.
func (o *NoProfileMatchInfo1) HasQueryParamCombinationList() bool {
	if o != nil && !IsNil(o.QueryParamCombinationList) {
		return true
	}

	return false
}

// SetQueryParamCombinationList gets a reference to the given []QueryParamCombination and assigns it to the QueryParamCombinationList field.
func (o *NoProfileMatchInfo1) SetQueryParamCombinationList(v []QueryParamCombination) {
	o.QueryParamCombinationList = v
}

func (o NoProfileMatchInfo1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["reason"] = o.Reason
	if !IsNil(o.QueryParamCombinationList) {
		toSerialize["queryParamCombinationList"] = o.QueryParamCombinationList
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableNoProfileMatchInfo1 struct {
	value *NoProfileMatchInfo1
	isSet bool
}

func (v NullableNoProfileMatchInfo1) Get() *NoProfileMatchInfo1 {
	return v.value
}

func (v *NullableNoProfileMatchInfo1) Set(val *NoProfileMatchInfo1) {
	v.value = val
	v.isSet = true
}

func (v NullableNoProfileMatchInfo1) IsSet() bool {
	return v.isSet
}

func (v *NullableNoProfileMatchInfo1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNoProfileMatchInfo1(val *NoProfileMatchInfo1) *NullableNoProfileMatchInfo1 {
	return &NullableNoProfileMatchInfo1{value: val, isSet: true}
}

func (v NullableNoProfileMatchInfo1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNoProfileMatchInfo1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
