// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
NRF NFDiscovery Service

NRF NFDiscovery Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nnrf_NFDiscovery

import (
	"encoding/json"
)

// checks if the DnnInfoItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DnnInfoItem{}

// DnnInfoItem Set of parameters supported by NF for a given DNN
type DnnInfoItem struct {
	Dnn                  DnnSmfInfoItemDnn `json:"dnn"`
	AdditionalProperties map[string]interface{}
}

type _DnnInfoItem DnnInfoItem

// NewDnnInfoItem instantiates a new DnnInfoItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDnnInfoItem(dnn DnnSmfInfoItemDnn) *DnnInfoItem {
	this := DnnInfoItem{}
	this.Dnn = dnn
	return &this
}

// NewDnnInfoItemWithDefaults instantiates a new DnnInfoItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDnnInfoItemWithDefaults() *DnnInfoItem {
	this := DnnInfoItem{}
	return &this
}

// GetDnn returns the Dnn field value
func (o *DnnInfoItem) GetDnn() DnnSmfInfoItemDnn {
	if o == nil {
		var ret DnnSmfInfoItemDnn
		return ret
	}

	return o.Dnn
}

// GetDnnOk returns a tuple with the Dnn field value
// and a boolean to check if the value has been set.
func (o *DnnInfoItem) GetDnnOk() (*DnnSmfInfoItemDnn, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dnn, true
}

// SetDnn sets field value
func (o *DnnInfoItem) SetDnn(v DnnSmfInfoItemDnn) {
	o.Dnn = v
}

func (o DnnInfoItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dnn"] = o.Dnn

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableDnnInfoItem struct {
	value *DnnInfoItem
	isSet bool
}

func (v NullableDnnInfoItem) Get() *DnnInfoItem {
	return v.value
}

func (v *NullableDnnInfoItem) Set(val *DnnInfoItem) {
	v.value = val
	v.isSet = true
}

func (v NullableDnnInfoItem) IsSet() bool {
	return v.isSet
}

func (v *NullableDnnInfoItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDnnInfoItem(val *DnnInfoItem) *NullableDnnInfoItem {
	return &NullableDnnInfoItem{value: val, isSet: true}
}

func (v NullableDnnInfoItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDnnInfoItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
