// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
NSSF NS Selection

Testing NetworkSliceInformationDocumentAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Nnssf_NSSelection

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_Nnssf_NSSelection_NetworkSliceInformationDocumentAPIService(t *testing.T) {

	configuration := NewConfiguration()
	apiClient := NewAPIClient(configuration)

	t.Run("Test NetworkSliceInformationDocumentAPIService NSSelectionGet", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.NetworkSliceInformationDocumentAPI.NSSelectionGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

}
