// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

Testing IndividualUeContextDocumentAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Namf_Communication

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_Namf_Communication_IndividualUeContextDocumentAPIService(t *testing.T) {

	configuration := NewConfiguration()
	apiClient := NewAPIClient(configuration)

	t.Run("Test IndividualUeContextDocumentAPIService CancelRelocateUEContext", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var ueContextId string

		httpRes, err := apiClient.IndividualUeContextDocumentAPI.CancelRelocateUEContext(context.Background(), ueContextId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test IndividualUeContextDocumentAPIService CreateUEContext", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var ueContextId string

		resp, httpRes, err := apiClient.IndividualUeContextDocumentAPI.CreateUEContext(context.Background(), ueContextId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test IndividualUeContextDocumentAPIService EBIAssignment", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var ueContextId string

		resp, httpRes, err := apiClient.IndividualUeContextDocumentAPI.EBIAssignment(context.Background(), ueContextId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test IndividualUeContextDocumentAPIService RegistrationStatusUpdate", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var ueContextId string

		resp, httpRes, err := apiClient.IndividualUeContextDocumentAPI.RegistrationStatusUpdate(context.Background(), ueContextId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test IndividualUeContextDocumentAPIService ReleaseUEContext", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var ueContextId string

		httpRes, err := apiClient.IndividualUeContextDocumentAPI.ReleaseUEContext(context.Background(), ueContextId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test IndividualUeContextDocumentAPIService RelocateUEContext", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var ueContextId string

		resp, httpRes, err := apiClient.IndividualUeContextDocumentAPI.RelocateUEContext(context.Background(), ueContextId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test IndividualUeContextDocumentAPIService UEContextTransfer", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var ueContextId string

		resp, httpRes, err := apiClient.IndividualUeContextDocumentAPI.UEContextTransfer(context.Background(), ueContextId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

}
