// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

Testing N1N2IndividualSubscriptionDocumentAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Namf_Communication

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_Namf_Communication_N1N2IndividualSubscriptionDocumentAPIService(t *testing.T) {

	configuration := NewConfiguration()
	apiClient := NewAPIClient(configuration)

	t.Run("Test N1N2IndividualSubscriptionDocumentAPIService N1N2MessageUnSubscribe", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var ueContextId string
		var subscriptionId string

		httpRes, err := apiClient.N1N2IndividualSubscriptionDocumentAPI.N1N2MessageUnSubscribe(context.Background(), ueContextId, subscriptionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

}
