// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

Testing N1N2SubscriptionsCollectionForIndividualUEContextsCollectionAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Namf_Communication

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_Namf_Communication_N1N2SubscriptionsCollectionForIndividualUEContextsCollectionAPIService(t *testing.T) {

	configuration := NewConfiguration()
	apiClient := NewAPIClient(configuration)

	t.Run("Test N1N2SubscriptionsCollectionForIndividualUEContextsCollectionAPIService N1N2MessageSubscribe", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var ueContextId string

		resp, httpRes, err := apiClient.N1N2SubscriptionsCollectionForIndividualUEContextsCollectionAPI.N1N2MessageSubscribe(context.Background(), ueContextId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

}
