// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

Testing IndividualSubscriptionDocumentAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Namf_Communication

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_Namf_Communication_IndividualSubscriptionDocumentAPIService(t *testing.T) {

	configuration := NewConfiguration()
	apiClient := NewAPIClient(configuration)

	t.Run("Test IndividualSubscriptionDocumentAPIService AMFStatusChangeSubscribeModfy", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var subscriptionId string

		resp, httpRes, err := apiClient.IndividualSubscriptionDocumentAPI.AMFStatusChangeSubscribeModfy(context.Background(), subscriptionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test IndividualSubscriptionDocumentAPIService AMFStatusChangeUnSubscribe", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var subscriptionId string

		httpRes, err := apiClient.IndividualSubscriptionDocumentAPI.AMFStatusChangeUnSubscribe(context.Background(), subscriptionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

}
