// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Namf_Communication

import (
	"encoding/json"
)

// checks if the CagInfo1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CagInfo1{}

// CagInfo1 contains CAG IDs.
type CagInfo1 struct {
	CagList              []string `json:"cagList"`
	AdditionalProperties map[string]interface{}
}

type _CagInfo1 CagInfo1

// NewCagInfo1 instantiates a new CagInfo1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCagInfo1(cagList []string) *CagInfo1 {
	this := CagInfo1{}
	this.CagList = cagList
	return &this
}

// NewCagInfo1WithDefaults instantiates a new CagInfo1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCagInfo1WithDefaults() *CagInfo1 {
	this := CagInfo1{}
	return &this
}

// GetCagList returns the CagList field value
func (o *CagInfo1) GetCagList() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.CagList
}

// GetCagListOk returns a tuple with the CagList field value
// and a boolean to check if the value has been set.
func (o *CagInfo1) GetCagListOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CagList, true
}

// SetCagList sets field value
func (o *CagInfo1) SetCagList(v []string) {
	o.CagList = v
}

func (o CagInfo1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cagList"] = o.CagList

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableCagInfo1 struct {
	value *CagInfo1
	isSet bool
}

func (v NullableCagInfo1) Get() *CagInfo1 {
	return v.value
}

func (v *NullableCagInfo1) Set(val *CagInfo1) {
	v.value = val
	v.isSet = true
}

func (v NullableCagInfo1) IsSet() bool {
	return v.isSet
}

func (v *NullableCagInfo1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCagInfo1(val *CagInfo1) *NullableCagInfo1 {
	return &NullableCagInfo1{value: val, isSet: true}
}

func (v NullableCagInfo1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCagInfo1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
