// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Namf_Communication

import (
	"encoding/json"
)

// checks if the RetainabilityThreshold type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RetainabilityThreshold{}

// RetainabilityThreshold struct for RetainabilityThreshold
type RetainabilityThreshold struct {
	AdditionalProperties map[string]interface{}
}

type _RetainabilityThreshold RetainabilityThreshold

// NewRetainabilityThreshold instantiates a new RetainabilityThreshold object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRetainabilityThreshold() *RetainabilityThreshold {
	this := RetainabilityThreshold{}
	return &this
}

// NewRetainabilityThresholdWithDefaults instantiates a new RetainabilityThreshold object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRetainabilityThresholdWithDefaults() *RetainabilityThreshold {
	this := RetainabilityThreshold{}
	return &this
}

func (o RetainabilityThreshold) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableRetainabilityThreshold struct {
	value *RetainabilityThreshold
	isSet bool
}

func (v NullableRetainabilityThreshold) Get() *RetainabilityThreshold {
	return v.value
}

func (v *NullableRetainabilityThreshold) Set(val *RetainabilityThreshold) {
	v.value = val
	v.isSet = true
}

func (v NullableRetainabilityThreshold) IsSet() bool {
	return v.isSet
}

func (v *NullableRetainabilityThreshold) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRetainabilityThreshold(val *RetainabilityThreshold) *NullableRetainabilityThreshold {
	return &NullableRetainabilityThreshold{value: val, isSet: true}
}

func (v NullableRetainabilityThreshold) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRetainabilityThreshold) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
