// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Namf_Communication

import (
	"encoding/json"
	"fmt"
)

// UpConnectionStatus UP Connection Status.
type UpConnectionStatus struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *UpConnectionStatus) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(UpConnectionStatus)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *UpConnectionStatus) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableUpConnectionStatus struct {
	value *UpConnectionStatus
	isSet bool
}

func (v NullableUpConnectionStatus) Get() *UpConnectionStatus {
	return v.value
}

func (v *NullableUpConnectionStatus) Set(val *UpConnectionStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableUpConnectionStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableUpConnectionStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpConnectionStatus(val *UpConnectionStatus) *NullableUpConnectionStatus {
	return &NullableUpConnectionStatus{value: val, isSet: true}
}

func (v NullableUpConnectionStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpConnectionStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
