// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Namf_Communication

import (
	"encoding/json"
)

// checks if the PduSessionInfo1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PduSessionInfo1{}

// PduSessionInfo1 Represents combination of PDU Session parameter(s) information.
type PduSessionInfo1 struct {
	PduSessType          *PduSessionType `json:"pduSessType,omitempty"`
	SscMode              *SscMode        `json:"sscMode,omitempty"`
	AccessTypes          []AccessType    `json:"accessTypes,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PduSessionInfo1 PduSessionInfo1

// NewPduSessionInfo1 instantiates a new PduSessionInfo1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPduSessionInfo1() *PduSessionInfo1 {
	this := PduSessionInfo1{}
	return &this
}

// NewPduSessionInfo1WithDefaults instantiates a new PduSessionInfo1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPduSessionInfo1WithDefaults() *PduSessionInfo1 {
	this := PduSessionInfo1{}
	return &this
}

// GetPduSessType returns the PduSessType field value if set, zero value otherwise.
func (o *PduSessionInfo1) GetPduSessType() PduSessionType {
	if o == nil || IsNil(o.PduSessType) {
		var ret PduSessionType
		return ret
	}
	return *o.PduSessType
}

// GetPduSessTypeOk returns a tuple with the PduSessType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionInfo1) GetPduSessTypeOk() (*PduSessionType, bool) {
	if o == nil || IsNil(o.PduSessType) {
		return nil, false
	}
	return o.PduSessType, true
}

// HasPduSessType returns a boolean if a field has been set.
func (o *PduSessionInfo1) HasPduSessType() bool {
	if o != nil && !IsNil(o.PduSessType) {
		return true
	}

	return false
}

// SetPduSessType gets a reference to the given PduSessionType and assigns it to the PduSessType field.
func (o *PduSessionInfo1) SetPduSessType(v PduSessionType) {
	o.PduSessType = &v
}

// GetSscMode returns the SscMode field value if set, zero value otherwise.
func (o *PduSessionInfo1) GetSscMode() SscMode {
	if o == nil || IsNil(o.SscMode) {
		var ret SscMode
		return ret
	}
	return *o.SscMode
}

// GetSscModeOk returns a tuple with the SscMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionInfo1) GetSscModeOk() (*SscMode, bool) {
	if o == nil || IsNil(o.SscMode) {
		return nil, false
	}
	return o.SscMode, true
}

// HasSscMode returns a boolean if a field has been set.
func (o *PduSessionInfo1) HasSscMode() bool {
	if o != nil && !IsNil(o.SscMode) {
		return true
	}

	return false
}

// SetSscMode gets a reference to the given SscMode and assigns it to the SscMode field.
func (o *PduSessionInfo1) SetSscMode(v SscMode) {
	o.SscMode = &v
}

// GetAccessTypes returns the AccessTypes field value if set, zero value otherwise.
func (o *PduSessionInfo1) GetAccessTypes() []AccessType {
	if o == nil || IsNil(o.AccessTypes) {
		var ret []AccessType
		return ret
	}
	return o.AccessTypes
}

// GetAccessTypesOk returns a tuple with the AccessTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionInfo1) GetAccessTypesOk() ([]AccessType, bool) {
	if o == nil || IsNil(o.AccessTypes) {
		return nil, false
	}
	return o.AccessTypes, true
}

// HasAccessTypes returns a boolean if a field has been set.
func (o *PduSessionInfo1) HasAccessTypes() bool {
	if o != nil && !IsNil(o.AccessTypes) {
		return true
	}

	return false
}

// SetAccessTypes gets a reference to the given []AccessType and assigns it to the AccessTypes field.
func (o *PduSessionInfo1) SetAccessTypes(v []AccessType) {
	o.AccessTypes = v
}

func (o PduSessionInfo1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PduSessType) {
		toSerialize["pduSessType"] = o.PduSessType
	}
	if !IsNil(o.SscMode) {
		toSerialize["sscMode"] = o.SscMode
	}
	if !IsNil(o.AccessTypes) {
		toSerialize["accessTypes"] = o.AccessTypes
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullablePduSessionInfo1 struct {
	value *PduSessionInfo1
	isSet bool
}

func (v NullablePduSessionInfo1) Get() *PduSessionInfo1 {
	return v.value
}

func (v *NullablePduSessionInfo1) Set(val *PduSessionInfo1) {
	v.value = val
	v.isSet = true
}

func (v NullablePduSessionInfo1) IsSet() bool {
	return v.isSet
}

func (v *NullablePduSessionInfo1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePduSessionInfo1(val *PduSessionInfo1) *NullablePduSessionInfo1 {
	return &NullablePduSessionInfo1{value: val, isSet: true}
}

func (v NullablePduSessionInfo1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePduSessionInfo1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
