// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Namf_Communication

import (
	"encoding/json"
)

// checks if the AmPolicyInfoContainer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AmPolicyInfoContainer{}

// AmPolicyInfoContainer AM Policy Information Container
type AmPolicyInfoContainer struct {
	// A map(list of key-value pairs) where Snssai serves as key.
	SliceUsgCtrlInfoSets *map[string]SliceUsageControlInfo `json:"sliceUsgCtrlInfoSets,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AmPolicyInfoContainer AmPolicyInfoContainer

// NewAmPolicyInfoContainer instantiates a new AmPolicyInfoContainer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAmPolicyInfoContainer() *AmPolicyInfoContainer {
	this := AmPolicyInfoContainer{}
	return &this
}

// NewAmPolicyInfoContainerWithDefaults instantiates a new AmPolicyInfoContainer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAmPolicyInfoContainerWithDefaults() *AmPolicyInfoContainer {
	this := AmPolicyInfoContainer{}
	return &this
}

// GetSliceUsgCtrlInfoSets returns the SliceUsgCtrlInfoSets field value if set, zero value otherwise.
func (o *AmPolicyInfoContainer) GetSliceUsgCtrlInfoSets() map[string]SliceUsageControlInfo {
	if o == nil || IsNil(o.SliceUsgCtrlInfoSets) {
		var ret map[string]SliceUsageControlInfo
		return ret
	}
	return *o.SliceUsgCtrlInfoSets
}

// GetSliceUsgCtrlInfoSetsOk returns a tuple with the SliceUsgCtrlInfoSets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AmPolicyInfoContainer) GetSliceUsgCtrlInfoSetsOk() (*map[string]SliceUsageControlInfo, bool) {
	if o == nil || IsNil(o.SliceUsgCtrlInfoSets) {
		return nil, false
	}
	return o.SliceUsgCtrlInfoSets, true
}

// HasSliceUsgCtrlInfoSets returns a boolean if a field has been set.
func (o *AmPolicyInfoContainer) HasSliceUsgCtrlInfoSets() bool {
	if o != nil && !IsNil(o.SliceUsgCtrlInfoSets) {
		return true
	}

	return false
}

// SetSliceUsgCtrlInfoSets gets a reference to the given map[string]SliceUsageControlInfo and assigns it to the SliceUsgCtrlInfoSets field.
func (o *AmPolicyInfoContainer) SetSliceUsgCtrlInfoSets(v map[string]SliceUsageControlInfo) {
	o.SliceUsgCtrlInfoSets = &v
}

func (o AmPolicyInfoContainer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SliceUsgCtrlInfoSets) {
		toSerialize["sliceUsgCtrlInfoSets"] = o.SliceUsgCtrlInfoSets
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableAmPolicyInfoContainer struct {
	value *AmPolicyInfoContainer
	isSet bool
}

func (v NullableAmPolicyInfoContainer) Get() *AmPolicyInfoContainer {
	return v.value
}

func (v *NullableAmPolicyInfoContainer) Set(val *AmPolicyInfoContainer) {
	v.value = val
	v.isSet = true
}

func (v NullableAmPolicyInfoContainer) IsSet() bool {
	return v.isSet
}

func (v *NullableAmPolicyInfoContainer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAmPolicyInfoContainer(val *AmPolicyInfoContainer) *NullableAmPolicyInfoContainer {
	return &NullableAmPolicyInfoContainer{value: val, isSet: true}
}

func (v NullableAmPolicyInfoContainer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAmPolicyInfoContainer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
