// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Namf_Communication

import (
	"encoding/json"
	"fmt"
)

// NetworkPerfOrderCriterion Represents the ordering criterion for the list of network performance analytics.   Possible values are:     - NUMBER_OF_UES: The ordering criterion of the analytics is the number of UEs.   - COMMUNICATION_PERF: The ordering criterion of the analytics is the communication performance.   - MOBILITY_PERF: The ordering criterion of the analytics is themobility performance.
type NetworkPerfOrderCriterion struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *NetworkPerfOrderCriterion) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(NetworkPerfOrderCriterion)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *NetworkPerfOrderCriterion) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableNetworkPerfOrderCriterion struct {
	value *NetworkPerfOrderCriterion
	isSet bool
}

func (v NullableNetworkPerfOrderCriterion) Get() *NetworkPerfOrderCriterion {
	return v.value
}

func (v *NullableNetworkPerfOrderCriterion) Set(val *NetworkPerfOrderCriterion) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkPerfOrderCriterion) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkPerfOrderCriterion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkPerfOrderCriterion(val *NetworkPerfOrderCriterion) *NullableNetworkPerfOrderCriterion {
	return &NullableNetworkPerfOrderCriterion{value: val, isSet: true}
}

func (v NullableNetworkPerfOrderCriterion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkPerfOrderCriterion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
