// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Namf_Communication

import (
	"encoding/json"
)

// checks if the MovBehavReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MovBehavReq{}

// MovBehavReq Represents the Movement Behaviour analytics requirements.
type MovBehavReq struct {
	LocationGranReq      *LocInfoGranularity `json:"locationGranReq,omitempty"`
	ReportThresholds     *ThresholdLevel     `json:"reportThresholds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MovBehavReq MovBehavReq

// NewMovBehavReq instantiates a new MovBehavReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMovBehavReq() *MovBehavReq {
	this := MovBehavReq{}
	return &this
}

// NewMovBehavReqWithDefaults instantiates a new MovBehavReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMovBehavReqWithDefaults() *MovBehavReq {
	this := MovBehavReq{}
	return &this
}

// GetLocationGranReq returns the LocationGranReq field value if set, zero value otherwise.
func (o *MovBehavReq) GetLocationGranReq() LocInfoGranularity {
	if o == nil || IsNil(o.LocationGranReq) {
		var ret LocInfoGranularity
		return ret
	}
	return *o.LocationGranReq
}

// GetLocationGranReqOk returns a tuple with the LocationGranReq field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MovBehavReq) GetLocationGranReqOk() (*LocInfoGranularity, bool) {
	if o == nil || IsNil(o.LocationGranReq) {
		return nil, false
	}
	return o.LocationGranReq, true
}

// HasLocationGranReq returns a boolean if a field has been set.
func (o *MovBehavReq) HasLocationGranReq() bool {
	if o != nil && !IsNil(o.LocationGranReq) {
		return true
	}

	return false
}

// SetLocationGranReq gets a reference to the given LocInfoGranularity and assigns it to the LocationGranReq field.
func (o *MovBehavReq) SetLocationGranReq(v LocInfoGranularity) {
	o.LocationGranReq = &v
}

// GetReportThresholds returns the ReportThresholds field value if set, zero value otherwise.
func (o *MovBehavReq) GetReportThresholds() ThresholdLevel {
	if o == nil || IsNil(o.ReportThresholds) {
		var ret ThresholdLevel
		return ret
	}
	return *o.ReportThresholds
}

// GetReportThresholdsOk returns a tuple with the ReportThresholds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MovBehavReq) GetReportThresholdsOk() (*ThresholdLevel, bool) {
	if o == nil || IsNil(o.ReportThresholds) {
		return nil, false
	}
	return o.ReportThresholds, true
}

// HasReportThresholds returns a boolean if a field has been set.
func (o *MovBehavReq) HasReportThresholds() bool {
	if o != nil && !IsNil(o.ReportThresholds) {
		return true
	}

	return false
}

// SetReportThresholds gets a reference to the given ThresholdLevel and assigns it to the ReportThresholds field.
func (o *MovBehavReq) SetReportThresholds(v ThresholdLevel) {
	o.ReportThresholds = &v
}

func (o MovBehavReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LocationGranReq) {
		toSerialize["locationGranReq"] = o.LocationGranReq
	}
	if !IsNil(o.ReportThresholds) {
		toSerialize["reportThresholds"] = o.ReportThresholds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableMovBehavReq struct {
	value *MovBehavReq
	isSet bool
}

func (v NullableMovBehavReq) Get() *MovBehavReq {
	return v.value
}

func (v *NullableMovBehavReq) Set(val *MovBehavReq) {
	v.value = val
	v.isSet = true
}

func (v NullableMovBehavReq) IsSet() bool {
	return v.isSet
}

func (v *NullableMovBehavReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMovBehavReq(val *MovBehavReq) *NullableMovBehavReq {
	return &NullableMovBehavReq{value: val, isSet: true}
}

func (v NullableMovBehavReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMovBehavReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
