// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Namf_Communication

import (
	"encoding/json"
	"fmt"
)

// E2eDataVolTransTimeCriterion Represents the ordering criterion for the list of E2E data volume transfer time.   Possible values are:     - TIME_SLOT_START: Indicates the order of time slot start.   - E2E_DATA_VOL_TRANS_TIME: The ordering criterion is the E2E data volume transfer time.
type E2eDataVolTransTimeCriterion struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *E2eDataVolTransTimeCriterion) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(E2eDataVolTransTimeCriterion)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *E2eDataVolTransTimeCriterion) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableE2eDataVolTransTimeCriterion struct {
	value *E2eDataVolTransTimeCriterion
	isSet bool
}

func (v NullableE2eDataVolTransTimeCriterion) Get() *E2eDataVolTransTimeCriterion {
	return v.value
}

func (v *NullableE2eDataVolTransTimeCriterion) Set(val *E2eDataVolTransTimeCriterion) {
	v.value = val
	v.isSet = true
}

func (v NullableE2eDataVolTransTimeCriterion) IsSet() bool {
	return v.isSet
}

func (v *NullableE2eDataVolTransTimeCriterion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableE2eDataVolTransTimeCriterion(val *E2eDataVolTransTimeCriterion) *NullableE2eDataVolTransTimeCriterion {
	return &NullableE2eDataVolTransTimeCriterion{value: val, isSet: true}
}

func (v NullableE2eDataVolTransTimeCriterion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableE2eDataVolTransTimeCriterion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
