// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Namf_Communication

import (
	"encoding/json"
)

// checks if the SnssaiDnnItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SnssaiDnnItem{}

// SnssaiDnnItem Combination of S-NSSAIs and DNNs
type SnssaiDnnItem struct {
	SnssaiList           []ExtSnssai
	DnnList              []string
	AdditionalProperties map[string]interface{}
}

type _SnssaiDnnItem SnssaiDnnItem

// NewSnssaiDnnItem instantiates a new SnssaiDnnItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSnssaiDnnItem() *SnssaiDnnItem {
	this := SnssaiDnnItem{}
	return &this
}

// NewSnssaiDnnItemWithDefaults instantiates a new SnssaiDnnItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSnssaiDnnItemWithDefaults() *SnssaiDnnItem {
	this := SnssaiDnnItem{}
	return &this
}

// GetSnssaiList returns the SnssaiList field value if set, zero value otherwise.
func (o *SnssaiDnnItem) GetSnssaiList() []ExtSnssai {
	if o == nil || IsNil(o.SnssaiList) {
		var ret []ExtSnssai
		return ret
	}
	return o.SnssaiList
}

// GetSnssaiListOk returns a tuple with the SnssaiList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SnssaiDnnItem) GetSnssaiListOk() ([]ExtSnssai, bool) {
	if o == nil || IsNil(o.SnssaiList) {
		return nil, false
	}
	return o.SnssaiList, true
}

// HasSnssaiList returns a boolean if a field has been set.
func (o *SnssaiDnnItem) HasSnssaiList() bool {
	if o != nil && !IsNil(o.SnssaiList) {
		return true
	}

	return false
}

// SetSnssaiList gets a reference to the given []ExtSnssai and assigns it to the SnssaiList field.
func (o *SnssaiDnnItem) SetSnssaiList(v []ExtSnssai) {
	o.SnssaiList = v
}

// GetDnnList returns the DnnList field value if set, zero value otherwise.
func (o *SnssaiDnnItem) GetDnnList() []string {
	if o == nil || IsNil(o.DnnList) {
		var ret []string
		return ret
	}
	return o.DnnList
}

// GetDnnListOk returns a tuple with the DnnList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SnssaiDnnItem) GetDnnListOk() ([]string, bool) {
	if o == nil || IsNil(o.DnnList) {
		return nil, false
	}
	return o.DnnList, true
}

// HasDnnList returns a boolean if a field has been set.
func (o *SnssaiDnnItem) HasDnnList() bool {
	if o != nil && !IsNil(o.DnnList) {
		return true
	}

	return false
}

// SetDnnList gets a reference to the given []string and assigns it to the DnnList field.
func (o *SnssaiDnnItem) SetDnnList(v []string) {
	o.DnnList = v
}

func (o SnssaiDnnItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SnssaiList) {
		toSerialize["snssaiList"] = o.SnssaiList
	}
	if !IsNil(o.DnnList) {
		toSerialize["dnnList"] = o.DnnList
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableSnssaiDnnItem struct {
	value *SnssaiDnnItem
	isSet bool
}

func (v NullableSnssaiDnnItem) Get() *SnssaiDnnItem {
	return v.value
}

func (v *NullableSnssaiDnnItem) Set(val *SnssaiDnnItem) {
	v.value = val
	v.isSet = true
}

func (v NullableSnssaiDnnItem) IsSet() bool {
	return v.isSet
}

func (v *NullableSnssaiDnnItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSnssaiDnnItem(val *SnssaiDnnItem) *NullableSnssaiDnnItem {
	return &NullableSnssaiDnnItem{value: val, isSet: true}
}

func (v NullableSnssaiDnnItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSnssaiDnnItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
