// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Namf_Communication

import (
	"encoding/json"
	"fmt"
)

// RecurType Indicates the recurrence applicable to a time window.
type RecurType struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *RecurType) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(RecurType)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *RecurType) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableRecurType struct {
	value *RecurType
	isSet bool
}

func (v NullableRecurType) Get() *RecurType {
	return v.value
}

func (v *NullableRecurType) Set(val *RecurType) {
	v.value = val
	v.isSet = true
}

func (v NullableRecurType) IsSet() bool {
	return v.isSet
}

func (v *NullableRecurType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecurType(val *RecurType) *NullableRecurType {
	return &NullableRecurType{value: val, isSet: true}
}

func (v NullableRecurType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecurType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
