// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Namf_Communication

import (
	"encoding/json"
	"fmt"
)

// UserDataConOrderCrit Represents the cause for requesting to terminate an analytics subscription.   Possible values are:     - APPLICABLE_TIME_WINDOW: The ordering criterion is the Applicable Time Window.   - NETWORK_STATUS_INDICATION: The ordering criterion is the network status indication.
type UserDataConOrderCrit struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *UserDataConOrderCrit) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(UserDataConOrderCrit)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *UserDataConOrderCrit) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableUserDataConOrderCrit struct {
	value *UserDataConOrderCrit
	isSet bool
}

func (v NullableUserDataConOrderCrit) Get() *UserDataConOrderCrit {
	return v.value
}

func (v *NullableUserDataConOrderCrit) Set(val *UserDataConOrderCrit) {
	v.value = val
	v.isSet = true
}

func (v NullableUserDataConOrderCrit) IsSet() bool {
	return v.isSet
}

func (v *NullableUserDataConOrderCrit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserDataConOrderCrit(val *UserDataConOrderCrit) *NullableUserDataConOrderCrit {
	return &NullableUserDataConOrderCrit{value: val, isSet: true}
}

func (v NullableUserDataConOrderCrit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserDataConOrderCrit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
