// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Namf_Communication

import (
	"encoding/json"
)

// checks if the LocAccuracyPerMethod type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LocAccuracyPerMethod{}

// LocAccuracyPerMethod Contains location accuracy analytics per positioning method.
type LocAccuracyPerMethod struct {
	PosMethod PositioningMethod `json:"posMethod"`
	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	LocAcc int32 `json:"locAcc"`
	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	LosNlosPct *int32 `json:"losNlosPct,omitempty"`
	// Indicates whether the target location is measured with LOS or NLOS.
	LosNlosInd           *bool `json:"losNlosInd,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LocAccuracyPerMethod LocAccuracyPerMethod

// NewLocAccuracyPerMethod instantiates a new LocAccuracyPerMethod object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocAccuracyPerMethod(posMethod PositioningMethod, locAcc int32) *LocAccuracyPerMethod {
	this := LocAccuracyPerMethod{}
	this.PosMethod = posMethod
	this.LocAcc = locAcc
	return &this
}

// NewLocAccuracyPerMethodWithDefaults instantiates a new LocAccuracyPerMethod object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocAccuracyPerMethodWithDefaults() *LocAccuracyPerMethod {
	this := LocAccuracyPerMethod{}
	return &this
}

// GetPosMethod returns the PosMethod field value
func (o *LocAccuracyPerMethod) GetPosMethod() PositioningMethod {
	if o == nil {
		var ret PositioningMethod
		return ret
	}

	return o.PosMethod
}

// GetPosMethodOk returns a tuple with the PosMethod field value
// and a boolean to check if the value has been set.
func (o *LocAccuracyPerMethod) GetPosMethodOk() (*PositioningMethod, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PosMethod, true
}

// SetPosMethod sets field value
func (o *LocAccuracyPerMethod) SetPosMethod(v PositioningMethod) {
	o.PosMethod = v
}

// GetLocAcc returns the LocAcc field value
func (o *LocAccuracyPerMethod) GetLocAcc() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LocAcc
}

// GetLocAccOk returns a tuple with the LocAcc field value
// and a boolean to check if the value has been set.
func (o *LocAccuracyPerMethod) GetLocAccOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LocAcc, true
}

// SetLocAcc sets field value
func (o *LocAccuracyPerMethod) SetLocAcc(v int32) {
	o.LocAcc = v
}

// GetLosNlosPct returns the LosNlosPct field value if set, zero value otherwise.
func (o *LocAccuracyPerMethod) GetLosNlosPct() int32 {
	if o == nil || IsNil(o.LosNlosPct) {
		var ret int32
		return ret
	}
	return *o.LosNlosPct
}

// GetLosNlosPctOk returns a tuple with the LosNlosPct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocAccuracyPerMethod) GetLosNlosPctOk() (*int32, bool) {
	if o == nil || IsNil(o.LosNlosPct) {
		return nil, false
	}
	return o.LosNlosPct, true
}

// HasLosNlosPct returns a boolean if a field has been set.
func (o *LocAccuracyPerMethod) HasLosNlosPct() bool {
	if o != nil && !IsNil(o.LosNlosPct) {
		return true
	}

	return false
}

// SetLosNlosPct gets a reference to the given int32 and assigns it to the LosNlosPct field.
func (o *LocAccuracyPerMethod) SetLosNlosPct(v int32) {
	o.LosNlosPct = &v
}

// GetLosNlosInd returns the LosNlosInd field value if set, zero value otherwise.
func (o *LocAccuracyPerMethod) GetLosNlosInd() bool {
	if o == nil || IsNil(o.LosNlosInd) {
		var ret bool
		return ret
	}
	return *o.LosNlosInd
}

// GetLosNlosIndOk returns a tuple with the LosNlosInd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocAccuracyPerMethod) GetLosNlosIndOk() (*bool, bool) {
	if o == nil || IsNil(o.LosNlosInd) {
		return nil, false
	}
	return o.LosNlosInd, true
}

// HasLosNlosInd returns a boolean if a field has been set.
func (o *LocAccuracyPerMethod) HasLosNlosInd() bool {
	if o != nil && !IsNil(o.LosNlosInd) {
		return true
	}

	return false
}

// SetLosNlosInd gets a reference to the given bool and assigns it to the LosNlosInd field.
func (o *LocAccuracyPerMethod) SetLosNlosInd(v bool) {
	o.LosNlosInd = &v
}

func (o LocAccuracyPerMethod) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["posMethod"] = o.PosMethod
	toSerialize["locAcc"] = o.LocAcc
	if !IsNil(o.LosNlosPct) {
		toSerialize["losNlosPct"] = o.LosNlosPct
	}
	if !IsNil(o.LosNlosInd) {
		toSerialize["losNlosInd"] = o.LosNlosInd
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableLocAccuracyPerMethod struct {
	value *LocAccuracyPerMethod
	isSet bool
}

func (v NullableLocAccuracyPerMethod) Get() *LocAccuracyPerMethod {
	return v.value
}

func (v *NullableLocAccuracyPerMethod) Set(val *LocAccuracyPerMethod) {
	v.value = val
	v.isSet = true
}

func (v NullableLocAccuracyPerMethod) IsSet() bool {
	return v.isSet
}

func (v *NullableLocAccuracyPerMethod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocAccuracyPerMethod(val *LocAccuracyPerMethod) *NullableLocAccuracyPerMethod {
	return &NullableLocAccuracyPerMethod{value: val, isSet: true}
}

func (v NullableLocAccuracyPerMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocAccuracyPerMethod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
