// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Namf_Communication

import (
	"encoding/json"
	"fmt"
)

// TrafficDirection Represents the traffic direction for the resource usage information.   Possible values are:     - UL_AND_DL: Uplink and downlink traffic.   - UL: Uplink traffic.   - DL: Downlink traffic.
type TrafficDirection struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *TrafficDirection) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(TrafficDirection)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *TrafficDirection) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableTrafficDirection struct {
	value *TrafficDirection
	isSet bool
}

func (v NullableTrafficDirection) Get() *TrafficDirection {
	return v.value
}

func (v *NullableTrafficDirection) Set(val *TrafficDirection) {
	v.value = val
	v.isSet = true
}

func (v NullableTrafficDirection) IsSet() bool {
	return v.isSet
}

func (v *NullableTrafficDirection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrafficDirection(val *TrafficDirection) *NullableTrafficDirection {
	return &NullableTrafficDirection{value: val, isSet: true}
}

func (v NullableTrafficDirection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrafficDirection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
