// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Namf_Communication

import (
	"encoding/json"
)

// checks if the TdTraffic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TdTraffic{}

// TdTraffic Represents traffic that matches or unmatches Traffic Descriptor of URSP rule.
type TdTraffic struct {
	PduSesTrafReqs []PduSesTrafficReq `json:"pduSesTrafReqs,omitempty"`
	// Unsigned integer identifying a volume in units of bytes.
	UlVol *int64 `json:"ulVol,omitempty"`
	// Unsigned integer identifying a volume in units of bytes.
	DlVol *int64 `json:"dlVol,omitempty"`
	// Unsigned integer identifying a volume in units of bytes.
	AllVol *int64 `json:"allVol,omitempty"`
	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	UlNumOfPkt *int32 `json:"ulNumOfPkt,omitempty"`
	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	DlNumOfPkt *int32 `json:"dlNumOfPkt,omitempty"`
	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	AllNumOfPkt          *int32 `json:"allNumOfPkt,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TdTraffic TdTraffic

// NewTdTraffic instantiates a new TdTraffic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTdTraffic() *TdTraffic {
	this := TdTraffic{}
	return &this
}

// NewTdTrafficWithDefaults instantiates a new TdTraffic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTdTrafficWithDefaults() *TdTraffic {
	this := TdTraffic{}
	return &this
}

// GetPduSesTrafReqs returns the PduSesTrafReqs field value if set, zero value otherwise.
func (o *TdTraffic) GetPduSesTrafReqs() []PduSesTrafficReq {
	if o == nil || IsNil(o.PduSesTrafReqs) {
		var ret []PduSesTrafficReq
		return ret
	}
	return o.PduSesTrafReqs
}

// GetPduSesTrafReqsOk returns a tuple with the PduSesTrafReqs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TdTraffic) GetPduSesTrafReqsOk() ([]PduSesTrafficReq, bool) {
	if o == nil || IsNil(o.PduSesTrafReqs) {
		return nil, false
	}
	return o.PduSesTrafReqs, true
}

// HasPduSesTrafReqs returns a boolean if a field has been set.
func (o *TdTraffic) HasPduSesTrafReqs() bool {
	if o != nil && !IsNil(o.PduSesTrafReqs) {
		return true
	}

	return false
}

// SetPduSesTrafReqs gets a reference to the given []PduSesTrafficReq and assigns it to the PduSesTrafReqs field.
func (o *TdTraffic) SetPduSesTrafReqs(v []PduSesTrafficReq) {
	o.PduSesTrafReqs = v
}

// GetUlVol returns the UlVol field value if set, zero value otherwise.
func (o *TdTraffic) GetUlVol() int64 {
	if o == nil || IsNil(o.UlVol) {
		var ret int64
		return ret
	}
	return *o.UlVol
}

// GetUlVolOk returns a tuple with the UlVol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TdTraffic) GetUlVolOk() (*int64, bool) {
	if o == nil || IsNil(o.UlVol) {
		return nil, false
	}
	return o.UlVol, true
}

// HasUlVol returns a boolean if a field has been set.
func (o *TdTraffic) HasUlVol() bool {
	if o != nil && !IsNil(o.UlVol) {
		return true
	}

	return false
}

// SetUlVol gets a reference to the given int64 and assigns it to the UlVol field.
func (o *TdTraffic) SetUlVol(v int64) {
	o.UlVol = &v
}

// GetDlVol returns the DlVol field value if set, zero value otherwise.
func (o *TdTraffic) GetDlVol() int64 {
	if o == nil || IsNil(o.DlVol) {
		var ret int64
		return ret
	}
	return *o.DlVol
}

// GetDlVolOk returns a tuple with the DlVol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TdTraffic) GetDlVolOk() (*int64, bool) {
	if o == nil || IsNil(o.DlVol) {
		return nil, false
	}
	return o.DlVol, true
}

// HasDlVol returns a boolean if a field has been set.
func (o *TdTraffic) HasDlVol() bool {
	if o != nil && !IsNil(o.DlVol) {
		return true
	}

	return false
}

// SetDlVol gets a reference to the given int64 and assigns it to the DlVol field.
func (o *TdTraffic) SetDlVol(v int64) {
	o.DlVol = &v
}

// GetAllVol returns the AllVol field value if set, zero value otherwise.
func (o *TdTraffic) GetAllVol() int64 {
	if o == nil || IsNil(o.AllVol) {
		var ret int64
		return ret
	}
	return *o.AllVol
}

// GetAllVolOk returns a tuple with the AllVol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TdTraffic) GetAllVolOk() (*int64, bool) {
	if o == nil || IsNil(o.AllVol) {
		return nil, false
	}
	return o.AllVol, true
}

// HasAllVol returns a boolean if a field has been set.
func (o *TdTraffic) HasAllVol() bool {
	if o != nil && !IsNil(o.AllVol) {
		return true
	}

	return false
}

// SetAllVol gets a reference to the given int64 and assigns it to the AllVol field.
func (o *TdTraffic) SetAllVol(v int64) {
	o.AllVol = &v
}

// GetUlNumOfPkt returns the UlNumOfPkt field value if set, zero value otherwise.
func (o *TdTraffic) GetUlNumOfPkt() int32 {
	if o == nil || IsNil(o.UlNumOfPkt) {
		var ret int32
		return ret
	}
	return *o.UlNumOfPkt
}

// GetUlNumOfPktOk returns a tuple with the UlNumOfPkt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TdTraffic) GetUlNumOfPktOk() (*int32, bool) {
	if o == nil || IsNil(o.UlNumOfPkt) {
		return nil, false
	}
	return o.UlNumOfPkt, true
}

// HasUlNumOfPkt returns a boolean if a field has been set.
func (o *TdTraffic) HasUlNumOfPkt() bool {
	if o != nil && !IsNil(o.UlNumOfPkt) {
		return true
	}

	return false
}

// SetUlNumOfPkt gets a reference to the given int32 and assigns it to the UlNumOfPkt field.
func (o *TdTraffic) SetUlNumOfPkt(v int32) {
	o.UlNumOfPkt = &v
}

// GetDlNumOfPkt returns the DlNumOfPkt field value if set, zero value otherwise.
func (o *TdTraffic) GetDlNumOfPkt() int32 {
	if o == nil || IsNil(o.DlNumOfPkt) {
		var ret int32
		return ret
	}
	return *o.DlNumOfPkt
}

// GetDlNumOfPktOk returns a tuple with the DlNumOfPkt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TdTraffic) GetDlNumOfPktOk() (*int32, bool) {
	if o == nil || IsNil(o.DlNumOfPkt) {
		return nil, false
	}
	return o.DlNumOfPkt, true
}

// HasDlNumOfPkt returns a boolean if a field has been set.
func (o *TdTraffic) HasDlNumOfPkt() bool {
	if o != nil && !IsNil(o.DlNumOfPkt) {
		return true
	}

	return false
}

// SetDlNumOfPkt gets a reference to the given int32 and assigns it to the DlNumOfPkt field.
func (o *TdTraffic) SetDlNumOfPkt(v int32) {
	o.DlNumOfPkt = &v
}

// GetAllNumOfPkt returns the AllNumOfPkt field value if set, zero value otherwise.
func (o *TdTraffic) GetAllNumOfPkt() int32 {
	if o == nil || IsNil(o.AllNumOfPkt) {
		var ret int32
		return ret
	}
	return *o.AllNumOfPkt
}

// GetAllNumOfPktOk returns a tuple with the AllNumOfPkt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TdTraffic) GetAllNumOfPktOk() (*int32, bool) {
	if o == nil || IsNil(o.AllNumOfPkt) {
		return nil, false
	}
	return o.AllNumOfPkt, true
}

// HasAllNumOfPkt returns a boolean if a field has been set.
func (o *TdTraffic) HasAllNumOfPkt() bool {
	if o != nil && !IsNil(o.AllNumOfPkt) {
		return true
	}

	return false
}

// SetAllNumOfPkt gets a reference to the given int32 and assigns it to the AllNumOfPkt field.
func (o *TdTraffic) SetAllNumOfPkt(v int32) {
	o.AllNumOfPkt = &v
}

func (o TdTraffic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PduSesTrafReqs) {
		toSerialize["pduSesTrafReqs"] = o.PduSesTrafReqs
	}
	if !IsNil(o.UlVol) {
		toSerialize["ulVol"] = o.UlVol
	}
	if !IsNil(o.DlVol) {
		toSerialize["dlVol"] = o.DlVol
	}
	if !IsNil(o.AllVol) {
		toSerialize["allVol"] = o.AllVol
	}
	if !IsNil(o.UlNumOfPkt) {
		toSerialize["ulNumOfPkt"] = o.UlNumOfPkt
	}
	if !IsNil(o.DlNumOfPkt) {
		toSerialize["dlNumOfPkt"] = o.DlNumOfPkt
	}
	if !IsNil(o.AllNumOfPkt) {
		toSerialize["allNumOfPkt"] = o.AllNumOfPkt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableTdTraffic struct {
	value *TdTraffic
	isSet bool
}

func (v NullableTdTraffic) Get() *TdTraffic {
	return v.value
}

func (v *NullableTdTraffic) Set(val *TdTraffic) {
	v.value = val
	v.isSet = true
}

func (v NullableTdTraffic) IsSet() bool {
	return v.isSet
}

func (v *NullableTdTraffic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTdTraffic(val *TdTraffic) *NullableTdTraffic {
	return &NullableTdTraffic{value: val, isSet: true}
}

func (v NullableTdTraffic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTdTraffic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
