// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Npcf_SMPolicyControl API

Testing IndividualSMPolicyDocumentAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Npcf_SMPolicyControl

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_Npcf_SMPolicyControl_IndividualSMPolicyDocumentAPIService(t *testing.T) {

	configuration := NewConfiguration()
	apiClient := NewAPIClient(configuration)

	t.Run("Test IndividualSMPolicyDocumentAPIService DeleteSMPolicy", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var smPolicyId string

		httpRes, err := apiClient.IndividualSMPolicyDocumentAPI.DeleteSMPolicy(context.Background(), smPolicyId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test IndividualSMPolicyDocumentAPIService GetSMPolicy", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var smPolicyId string

		resp, httpRes, err := apiClient.IndividualSMPolicyDocumentAPI.GetSMPolicy(context.Background(), smPolicyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test IndividualSMPolicyDocumentAPIService UpdateSMPolicy", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var smPolicyId string

		resp, httpRes, err := apiClient.IndividualSMPolicyDocumentAPI.UpdateSMPolicy(context.Background(), smPolicyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

}
