// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Npcf_SMPolicyControl API

Testing SMPoliciesCollectionAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Npcf_SMPolicyControl

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_Npcf_SMPolicyControl_SMPoliciesCollectionAPIService(t *testing.T) {

	configuration := NewConfiguration()
	apiClient := NewAPIClient(configuration)

	t.Run("Test SMPoliciesCollectionAPIService CreateSMPolicy", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.SMPoliciesCollectionAPI.CreateSMPolicy(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

}
