// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Npcf_SMPolicyControl API

Session Management Policy Control Service
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Npcf_SMPolicyControl

import (
	"encoding/json"
)

// checks if the SliceUsgCtrlInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SliceUsgCtrlInfo{}

// SliceUsgCtrlInfo Represents network slice usage control information.
type SliceUsgCtrlInfo struct {
	// indicating a time in seconds with OpenAPI defined 'nullable: true' property.
	PduSessInactivTimer  NullableInt32
	AdditionalProperties map[string]interface{}
}

type _SliceUsgCtrlInfo SliceUsgCtrlInfo

// NewSliceUsgCtrlInfo instantiates a new SliceUsgCtrlInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSliceUsgCtrlInfo() *SliceUsgCtrlInfo {
	this := SliceUsgCtrlInfo{}
	return &this
}

// NewSliceUsgCtrlInfoWithDefaults instantiates a new SliceUsgCtrlInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSliceUsgCtrlInfoWithDefaults() *SliceUsgCtrlInfo {
	this := SliceUsgCtrlInfo{}
	return &this
}

// GetPduSessInactivTimer returns the PduSessInactivTimer field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SliceUsgCtrlInfo) GetPduSessInactivTimer() int32 {
	if o == nil || IsNil(o.PduSessInactivTimer.Get()) {
		var ret int32
		return ret
	}
	return *o.PduSessInactivTimer.Get()
}

// GetPduSessInactivTimerOk returns a tuple with the PduSessInactivTimer field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SliceUsgCtrlInfo) GetPduSessInactivTimerOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PduSessInactivTimer.Get(), o.PduSessInactivTimer.IsSet()
}

// HasPduSessInactivTimer returns a boolean if a field has been set.
func (o *SliceUsgCtrlInfo) HasPduSessInactivTimer() bool {
	if o != nil && o.PduSessInactivTimer.IsSet() {
		return true
	}

	return false
}

// SetPduSessInactivTimer gets a reference to the given NullableInt32 and assigns it to the PduSessInactivTimer field.
func (o *SliceUsgCtrlInfo) SetPduSessInactivTimer(v int32) {
	o.PduSessInactivTimer.Set(&v)
}

// SetPduSessInactivTimerNil sets the value for PduSessInactivTimer to be an explicit nil
func (o *SliceUsgCtrlInfo) SetPduSessInactivTimerNil() {
	o.PduSessInactivTimer.Set(nil)
}

// UnsetPduSessInactivTimer ensures that no value is present for PduSessInactivTimer, not even an explicit nil
func (o *SliceUsgCtrlInfo) UnsetPduSessInactivTimer() {
	o.PduSessInactivTimer.Unset()
}

func (o SliceUsgCtrlInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.PduSessInactivTimer.IsSet() {
		toSerialize["pduSessInactivTimer"] = o.PduSessInactivTimer.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableSliceUsgCtrlInfo struct {
	value *SliceUsgCtrlInfo
	isSet bool
}

func (v NullableSliceUsgCtrlInfo) Get() *SliceUsgCtrlInfo {
	return v.value
}

func (v *NullableSliceUsgCtrlInfo) Set(val *SliceUsgCtrlInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableSliceUsgCtrlInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableSliceUsgCtrlInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSliceUsgCtrlInfo(val *SliceUsgCtrlInfo) *NullableSliceUsgCtrlInfo {
	return &NullableSliceUsgCtrlInfo{value: val, isSet: true}
}

func (v NullableSliceUsgCtrlInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSliceUsgCtrlInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
