// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Npcf_SMPolicyControl API

Session Management Policy Control Service
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Npcf_SMPolicyControl

import (
	"encoding/json"
	"fmt"
)

// AtsssCapability Contains the ATSSS capability supported for the MA PDU Session.
type AtsssCapability string

// List of AtsssCapability
const (
	ATSSSCAPABILITY_MPTCP_ATSSS_LL_WITH_ASMODE_UL                    AtsssCapability = "MPTCP_ATSSS_LL_WITH_ASMODE_UL"
	ATSSSCAPABILITY_MPTCP_ATSSS_LL_WITH_EXSDMODE_DL_ASMODE_UL        AtsssCapability = "MPTCP_ATSSS_LL_WITH_EXSDMODE_DL_ASMODE_UL"
	ATSSSCAPABILITY_MPTCP_ATSSS_LL_WITH_ASMODE_DLUL                  AtsssCapability = "MPTCP_ATSSS_LL_WITH_ASMODE_DLUL"
	ATSSSCAPABILITY_ATSSS_LL                                         AtsssCapability = "ATSSS_LL"
	ATSSSCAPABILITY_MPTCP_ATSSS_LL                                   AtsssCapability = "MPTCP_ATSSS_LL"
	ATSSSCAPABILITY_MPQUIC_ATSSS_LL_WITH_ASMODE_UL                   AtsssCapability = "MPQUIC_ATSSS_LL_WITH_ASMODE_UL"
	ATSSSCAPABILITY_MPQUIC_ATSSS_LL_WITH_EXSDMODE_DL_ASMODE_UL       AtsssCapability = "MPQUIC_ATSSS_LL_WITH_EXSDMODE_DL_ASMODE_UL"
	ATSSSCAPABILITY_MPQUIC_ATSSS_LL_WITH_ASMODE_DLUL                 AtsssCapability = "MPQUIC_ATSSS_LL_WITH_ASMODE_DLUL"
	ATSSSCAPABILITY_MPQUIC_ATSSS_LL                                  AtsssCapability = "MPQUIC_ATSSS_LL"
	ATSSSCAPABILITY_MPTCP_MPQUIC_ATSSS_LL_WITH_ASMODE_UL             AtsssCapability = "MPTCP_MPQUIC_ATSSS_LL_WITH_ASMODE_UL"
	ATSSSCAPABILITY_MPTCP_MPQUIC_ATSSS_LL_WITH_EXSDMODE_DL_ASMODE_UL AtsssCapability = "MPTCP_MPQUIC_ATSSS_LL_WITH_EXSDMODE_DL_ASMODE_UL"
	ATSSSCAPABILITY_MPTCP_MPQUIC_ATSSS_LL_WITH_ASMODE_DLUL           AtsssCapability = "MPTCP_MPQUIC_ATSSS_LL_WITH_ASMODE_DLUL"
	ATSSSCAPABILITY_MPTCP_MPQUIC_ATSSS_LL                            AtsssCapability = "MPTCP_MPQUIC_ATSSS_LL"
)

// All allowed values of AtsssCapability enum
var AllowedAtsssCapabilityEnumValues = []AtsssCapability{
	"MPTCP_ATSSS_LL_WITH_ASMODE_UL",
	"MPTCP_ATSSS_LL_WITH_EXSDMODE_DL_ASMODE_UL",
	"MPTCP_ATSSS_LL_WITH_ASMODE_DLUL",
	"ATSSS_LL",
	"MPTCP_ATSSS_LL",
	"MPQUIC_ATSSS_LL_WITH_ASMODE_UL",
	"MPQUIC_ATSSS_LL_WITH_EXSDMODE_DL_ASMODE_UL",
	"MPQUIC_ATSSS_LL_WITH_ASMODE_DLUL",
	"MPQUIC_ATSSS_LL",
	"MPTCP_MPQUIC_ATSSS_LL_WITH_ASMODE_UL",
	"MPTCP_MPQUIC_ATSSS_LL_WITH_EXSDMODE_DL_ASMODE_UL",
	"MPTCP_MPQUIC_ATSSS_LL_WITH_ASMODE_DLUL",
	"MPTCP_MPQUIC_ATSSS_LL",
}

func (v *AtsssCapability) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AtsssCapability(value)
	for _, existing := range AllowedAtsssCapabilityEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AtsssCapability", value)
}

// NewAtsssCapabilityFromValue returns a pointer to a valid AtsssCapability
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAtsssCapabilityFromValue(v string) (*AtsssCapability, error) {
	ev := AtsssCapability(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AtsssCapability: valid values are %v", v, AllowedAtsssCapabilityEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AtsssCapability) IsValid() bool {
	for _, existing := range AllowedAtsssCapabilityEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AtsssCapability value
func (v AtsssCapability) Ptr() *AtsssCapability {
	return &v
}

type NullableAtsssCapability struct {
	value *AtsssCapability
	isSet bool
}

func (v NullableAtsssCapability) Get() *AtsssCapability {
	return v.value
}

func (v *NullableAtsssCapability) Set(val *AtsssCapability) {
	v.value = val
	v.isSet = true
}

func (v NullableAtsssCapability) IsSet() bool {
	return v.isSet
}

func (v *NullableAtsssCapability) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAtsssCapability(val *AtsssCapability) *NullableAtsssCapability {
	return &NullableAtsssCapability{value: val, isSet: true}
}

func (v NullableAtsssCapability) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAtsssCapability) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
