// SPDX-FileCopyrightText: 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Npcf_SMPolicyControl API

Session Management Policy Control Service
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Npcf_SMPolicyControl

import (
	"encoding/json"
	"fmt"
)

// TransportMode Indicates the Transport Mode when the steering functionality is MPQUIC functionality.
type TransportMode struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *TransportMode) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(TransportMode)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *TransportMode) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableTransportMode struct {
	value *TransportMode
	isSet bool
}

func (v NullableTransportMode) Get() *TransportMode {
	return v.value
}

func (v *NullableTransportMode) Set(val *TransportMode) {
	v.value = val
	v.isSet = true
}

func (v NullableTransportMode) IsSet() bool {
	return v.isSet
}

func (v *NullableTransportMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransportMode(val *TransportMode) *NullableTransportMode {
	return &NullableTransportMode{value: val, isSet: true}
}

func (v NullableTransportMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransportMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
